
package Shipment::GSO::WSDL::Elements::AuthenticationHeader;
use strict;
use warnings;

{ # BLOCK to scope variables

sub get_xmlns { 'http://gso.com/GsoShipWS' }

__PACKAGE__->__set_name('AuthenticationHeader');
__PACKAGE__->__set_nillable();
__PACKAGE__->__set_minOccurs();
__PACKAGE__->__set_maxOccurs();
__PACKAGE__->__set_ref();
use base qw(
    SOAP::WSDL::XSD::Typelib::Element
    Shipment::GSO::WSDL::Types::AuthenticationHeader
);

}

1;


=pod

=head1 NAME

Shipment::GSO::WSDL::Elements::AuthenticationHeader

=head1 DESCRIPTION

Perl data type class for the XML Schema defined element
AuthenticationHeader from the namespace http://gso.com/GsoShipWS.







=head1 METHODS

=head2 new

 my $element = Shipment::GSO::WSDL::Elements::AuthenticationHeader->new($data);

Constructor. The following data structure may be passed to new():

 { # Shipment::GSO::WSDL::Types::AuthenticationHeader
   UserName =>  $some_value, # string
   Password =>  $some_value, # string
 },

=head1 AUTHOR

Generated by SOAP::WSDL

=cut

