
package Shipment::GSO::WSDL::Elements::GetDeliveryTimesResponse;
use strict;
use warnings;

{ # BLOCK to scope variables

sub get_xmlns { 'http://gso.com/GsoShipWS' }

__PACKAGE__->__set_name('GetDeliveryTimesResponse');
__PACKAGE__->__set_nillable();
__PACKAGE__->__set_minOccurs();
__PACKAGE__->__set_maxOccurs();
__PACKAGE__->__set_ref();

use base qw(
    SOAP::WSDL::XSD::Typelib::Element
    SOAP::WSDL::XSD::Typelib::ComplexType
);

our $XML_ATTRIBUTE_CLASS;
undef $XML_ATTRIBUTE_CLASS;

sub __get_attr_class {
    return $XML_ATTRIBUTE_CLASS;
}

use Class::Std::Fast::Storable constructor => 'none';
use base qw(SOAP::WSDL::XSD::Typelib::ComplexType);

Class::Std::initialize();

{ # BLOCK to scope variables

my %GetDeliveryTimesResult_of :ATTR(:get<GetDeliveryTimesResult>);

__PACKAGE__->_factory(
    [ qw(        GetDeliveryTimesResult

    ) ],
    {
        'GetDeliveryTimesResult' => \%GetDeliveryTimesResult_of,
    },
    {
        'GetDeliveryTimesResult' => 'Shipment::GSO::WSDL::Types::GetDeliveryTimesResult',
    },
    {

        'GetDeliveryTimesResult' => 'GetDeliveryTimesResult',
    }
);

} # end BLOCK






} # end of BLOCK



1;


=pod

=head1 NAME

Shipment::GSO::WSDL::Elements::GetDeliveryTimesResponse

=head1 DESCRIPTION

Perl data type class for the XML Schema defined element
GetDeliveryTimesResponse from the namespace http://gso.com/GsoShipWS.







=head1 PROPERTIES

The following properties may be accessed using get_PROPERTY / set_PROPERTY
methods:

=over

=item * GetDeliveryTimesResult

 $element->set_GetDeliveryTimesResult($data);
 $element->get_GetDeliveryTimesResult();





=back


=head1 METHODS

=head2 new

 my $element = Shipment::GSO::WSDL::Elements::GetDeliveryTimesResponse->new($data);

Constructor. The following data structure may be passed to new():

 {
   GetDeliveryTimesResult =>  { # Shipment::GSO::WSDL::Types::GetDeliveryTimesResult
     DeliveryTimesInfo =>  { # Shipment::GSO::WSDL::Types::ArrayOfDeliveryTimesInfo
       DeliveryTimesInfo =>  { # Shipment::GSO::WSDL::Types::DeliveryTimesInfo
         DeliveryLocation =>  { # Shipment::GSO::WSDL::Types::DeliveryLocation
           City =>  $some_value, # string
           ZipCode =>  $some_value, # string
         },
         DeliveryTimes =>  { # Shipment::GSO::WSDL::Types::ArrayOfDeliveryTime
           DeliveryTime =>  { # Shipment::GSO::WSDL::Types::DeliveryTime
             ServiceCode =>  $some_value, # string
             ServiceDescription =>  $some_value, # string
             GuaranteedDeliveryTime =>  $some_value, # string
           },
         },
       },
     },
     Result =>  { # Shipment::GSO::WSDL::Types::Result
       Code =>  $some_value, # int
       Message =>  $some_value, # string
     },
   },
 },

=head1 AUTHOR

Generated by SOAP::WSDL

=cut

