
package Shipment::GSO::WSDL::Elements::GetDropBoxInfoResponse;
use strict;
use warnings;

{ # BLOCK to scope variables

sub get_xmlns { 'http://gso.com/GsoShipWS' }

__PACKAGE__->__set_name('GetDropBoxInfoResponse');
__PACKAGE__->__set_nillable();
__PACKAGE__->__set_minOccurs();
__PACKAGE__->__set_maxOccurs();
__PACKAGE__->__set_ref();

use base qw(
    SOAP::WSDL::XSD::Typelib::Element
    SOAP::WSDL::XSD::Typelib::ComplexType
);

our $XML_ATTRIBUTE_CLASS;
undef $XML_ATTRIBUTE_CLASS;

sub __get_attr_class {
    return $XML_ATTRIBUTE_CLASS;
}

use Class::Std::Fast::Storable constructor => 'none';
use base qw(SOAP::WSDL::XSD::Typelib::ComplexType);

Class::Std::initialize();

{ # BLOCK to scope variables

my %GetDropBoxInfoResult_of :ATTR(:get<GetDropBoxInfoResult>);

__PACKAGE__->_factory(
    [ qw(        GetDropBoxInfoResult

    ) ],
    {
        'GetDropBoxInfoResult' => \%GetDropBoxInfoResult_of,
    },
    {
        'GetDropBoxInfoResult' => 'Shipment::GSO::WSDL::Types::GetDropBoxInfoResult',
    },
    {

        'GetDropBoxInfoResult' => 'GetDropBoxInfoResult',
    }
);

} # end BLOCK






} # end of BLOCK



1;


=pod

=head1 NAME

Shipment::GSO::WSDL::Elements::GetDropBoxInfoResponse

=head1 DESCRIPTION

Perl data type class for the XML Schema defined element
GetDropBoxInfoResponse from the namespace http://gso.com/GsoShipWS.







=head1 PROPERTIES

The following properties may be accessed using get_PROPERTY / set_PROPERTY
methods:

=over

=item * GetDropBoxInfoResult

 $element->set_GetDropBoxInfoResult($data);
 $element->get_GetDropBoxInfoResult();





=back


=head1 METHODS

=head2 new

 my $element = Shipment::GSO::WSDL::Elements::GetDropBoxInfoResponse->new($data);

Constructor. The following data structure may be passed to new():

 {
   GetDropBoxInfoResult =>  { # Shipment::GSO::WSDL::Types::GetDropBoxInfoResult
     DropBoxInfo =>  { # Shipment::GSO::WSDL::Types::ArrayOfDropBoxInfo
       DropBoxInfo =>  { # Shipment::GSO::WSDL::Types::DropBoxInfo
         Address =>  $some_value, # string
         City =>  $some_value, # string
         Zip =>  $some_value, # string
         Notes =>  $some_value, # string
         EstimatedPickupTime =>  $some_value, # string
       },
     },
     Result =>  { # Shipment::GSO::WSDL::Types::Result
       Code =>  $some_value, # int
       Message =>  $some_value, # string
     },
   },
 },

=head1 AUTHOR

Generated by SOAP::WSDL

=cut

