
package Shipment::GSO::WSDL::Elements::GetDeliveryTimes;
use strict;
use warnings;

{ # BLOCK to scope variables

sub get_xmlns { 'http://gso.com/GsoShipWS' }

__PACKAGE__->__set_name('GetDeliveryTimes');
__PACKAGE__->__set_nillable();
__PACKAGE__->__set_minOccurs();
__PACKAGE__->__set_maxOccurs();
__PACKAGE__->__set_ref();

use base qw(
    SOAP::WSDL::XSD::Typelib::Element
    SOAP::WSDL::XSD::Typelib::ComplexType
);

our $XML_ATTRIBUTE_CLASS;
undef $XML_ATTRIBUTE_CLASS;

sub __get_attr_class {
    return $XML_ATTRIBUTE_CLASS;
}

use Class::Std::Fast::Storable constructor => 'none';
use base qw(SOAP::WSDL::XSD::Typelib::ComplexType);

Class::Std::initialize();

{ # BLOCK to scope variables

my %DeliveryTimesRequest_of :ATTR(:get<DeliveryTimesRequest>);

__PACKAGE__->_factory(
    [ qw(        DeliveryTimesRequest

    ) ],
    {
        'DeliveryTimesRequest' => \%DeliveryTimesRequest_of,
    },
    {
        'DeliveryTimesRequest' => 'Shipment::GSO::WSDL::Types::GetDeliveryTimesRequest',
    },
    {

        'DeliveryTimesRequest' => 'DeliveryTimesRequest',
    }
);

} # end BLOCK






} # end of BLOCK



1;


=pod

=head1 NAME

Shipment::GSO::WSDL::Elements::GetDeliveryTimes

=head1 DESCRIPTION

Perl data type class for the XML Schema defined element
GetDeliveryTimes from the namespace http://gso.com/GsoShipWS.







=head1 PROPERTIES

The following properties may be accessed using get_PROPERTY / set_PROPERTY
methods:

=over

=item * DeliveryTimesRequest

 $element->set_DeliveryTimesRequest($data);
 $element->get_DeliveryTimesRequest();





=back


=head1 METHODS

=head2 new

 my $element = Shipment::GSO::WSDL::Elements::GetDeliveryTimes->new($data);

Constructor. The following data structure may be passed to new():

 {
   DeliveryTimesRequest =>  { # Shipment::GSO::WSDL::Types::GetDeliveryTimesRequest
     SearchType => $some_value, # DeliveryTimesSearchType
     SearchValue =>  $some_value, # string
   },
 },

=head1 AUTHOR

Generated by SOAP::WSDL

=cut

