
package Shipment::GSO::WSDL::Elements::GetShippingActivity;
use strict;
use warnings;

{ # BLOCK to scope variables

sub get_xmlns { 'http://gso.com/GsoShipWS' }

__PACKAGE__->__set_name('GetShippingActivity');
__PACKAGE__->__set_nillable();
__PACKAGE__->__set_minOccurs();
__PACKAGE__->__set_maxOccurs();
__PACKAGE__->__set_ref();

use base qw(
    SOAP::WSDL::XSD::Typelib::Element
    SOAP::WSDL::XSD::Typelib::ComplexType
);

our $XML_ATTRIBUTE_CLASS;
undef $XML_ATTRIBUTE_CLASS;

sub __get_attr_class {
    return $XML_ATTRIBUTE_CLASS;
}

use Class::Std::Fast::Storable constructor => 'none';
use base qw(SOAP::WSDL::XSD::Typelib::ComplexType);

Class::Std::initialize();

{ # BLOCK to scope variables

my %GetShippingActivityRequest_of :ATTR(:get<GetShippingActivityRequest>);

__PACKAGE__->_factory(
    [ qw(        GetShippingActivityRequest

    ) ],
    {
        'GetShippingActivityRequest' => \%GetShippingActivityRequest_of,
    },
    {
        'GetShippingActivityRequest' => 'Shipment::GSO::WSDL::Types::GetShippingActivityRequest',
    },
    {

        'GetShippingActivityRequest' => 'GetShippingActivityRequest',
    }
);

} # end BLOCK






} # end of BLOCK



1;


=pod

=head1 NAME

Shipment::GSO::WSDL::Elements::GetShippingActivity

=head1 DESCRIPTION

Perl data type class for the XML Schema defined element
GetShippingActivity from the namespace http://gso.com/GsoShipWS.







=head1 PROPERTIES

The following properties may be accessed using get_PROPERTY / set_PROPERTY
methods:

=over

=item * GetShippingActivityRequest

 $element->set_GetShippingActivityRequest($data);
 $element->get_GetShippingActivityRequest();





=back


=head1 METHODS

=head2 new

 my $element = Shipment::GSO::WSDL::Elements::GetShippingActivity->new($data);

Constructor. The following data structure may be passed to new():

 {
   GetShippingActivityRequest =>  { # Shipment::GSO::WSDL::Types::GetShippingActivityRequest
     AccountNumber =>  $some_value, # int
     SearchType => $some_value, # ShippingActivitySearchType
     SearchValue =>  $some_value, # string
   },
 },

=head1 AUTHOR

Generated by SOAP::WSDL

=cut

