
package Shipment::GSO::WSDL::Elements::GetShippingRateResponse;
use strict;
use warnings;

{ # BLOCK to scope variables

sub get_xmlns { 'http://gso.com/GsoShipWS' }

__PACKAGE__->__set_name('GetShippingRateResponse');
__PACKAGE__->__set_nillable();
__PACKAGE__->__set_minOccurs();
__PACKAGE__->__set_maxOccurs();
__PACKAGE__->__set_ref();

use base qw(
    SOAP::WSDL::XSD::Typelib::Element
    SOAP::WSDL::XSD::Typelib::ComplexType
);

our $XML_ATTRIBUTE_CLASS;
undef $XML_ATTRIBUTE_CLASS;

sub __get_attr_class {
    return $XML_ATTRIBUTE_CLASS;
}

use Class::Std::Fast::Storable constructor => 'none';
use base qw(SOAP::WSDL::XSD::Typelib::ComplexType);

Class::Std::initialize();

{ # BLOCK to scope variables

my %GetShippingRateResult_of :ATTR(:get<GetShippingRateResult>);

__PACKAGE__->_factory(
    [ qw(        GetShippingRateResult

    ) ],
    {
        'GetShippingRateResult' => \%GetShippingRateResult_of,
    },
    {
        'GetShippingRateResult' => 'Shipment::GSO::WSDL::Types::GetShippingRateResult',
    },
    {

        'GetShippingRateResult' => 'GetShippingRateResult',
    }
);

} # end BLOCK






} # end of BLOCK



1;


=pod

=head1 NAME

Shipment::GSO::WSDL::Elements::GetShippingRateResponse

=head1 DESCRIPTION

Perl data type class for the XML Schema defined element
GetShippingRateResponse from the namespace http://gso.com/GsoShipWS.







=head1 PROPERTIES

The following properties may be accessed using get_PROPERTY / set_PROPERTY
methods:

=over

=item * GetShippingRateResult

 $element->set_GetShippingRateResult($data);
 $element->get_GetShippingRateResult();





=back


=head1 METHODS

=head2 new

 my $element = Shipment::GSO::WSDL::Elements::GetShippingRateResponse->new($data);

Constructor. The following data structure may be passed to new():

 {
   GetShippingRateResult =>  { # Shipment::GSO::WSDL::Types::GetShippingRateResult
     ShipmentCharges =>  { # Shipment::GSO::WSDL::Types::ShipmentCharges
       TransportationCharge =>  $some_value, # decimal
       CODCharge =>  $some_value, # decimal
       InsuranceCharge =>  $some_value, # decimal
       OtherCharge =>  $some_value, # decimal
       FuelSurcharge =>  $some_value, # decimal
       TotalCharge =>  $some_value, # decimal
     },
     Result =>  { # Shipment::GSO::WSDL::Types::Result
       Code =>  $some_value, # int
       Message =>  $some_value, # string
     },
   },
 },

=head1 AUTHOR

Generated by SOAP::WSDL

=cut

