
package Shipment::GSO::WSDL::Elements::GetServiceTypes;
use strict;
use warnings;

{ # BLOCK to scope variables

sub get_xmlns { 'http://gso.com/GsoShipWS' }

__PACKAGE__->__set_name('GetServiceTypes');
__PACKAGE__->__set_nillable();
__PACKAGE__->__set_minOccurs();
__PACKAGE__->__set_maxOccurs();
__PACKAGE__->__set_ref();

use base qw(
    SOAP::WSDL::XSD::Typelib::Element
    SOAP::WSDL::XSD::Typelib::ComplexType
);

our $XML_ATTRIBUTE_CLASS;
undef $XML_ATTRIBUTE_CLASS;

sub __get_attr_class {
    return $XML_ATTRIBUTE_CLASS;
}

use Class::Std::Fast::Storable constructor => 'none';
use base qw(SOAP::WSDL::XSD::Typelib::ComplexType);

Class::Std::initialize();

{ # BLOCK to scope variables

my %GetServiceTypesRequest_of :ATTR(:get<GetServiceTypesRequest>);

__PACKAGE__->_factory(
    [ qw(        GetServiceTypesRequest

    ) ],
    {
        'GetServiceTypesRequest' => \%GetServiceTypesRequest_of,
    },
    {
        'GetServiceTypesRequest' => 'Shipment::GSO::WSDL::Types::GetServiceTypesRequest',
    },
    {

        'GetServiceTypesRequest' => 'GetServiceTypesRequest',
    }
);

} # end BLOCK






} # end of BLOCK



1;


=pod

=head1 NAME

Shipment::GSO::WSDL::Elements::GetServiceTypes

=head1 DESCRIPTION

Perl data type class for the XML Schema defined element
GetServiceTypes from the namespace http://gso.com/GsoShipWS.







=head1 PROPERTIES

The following properties may be accessed using get_PROPERTY / set_PROPERTY
methods:

=over

=item * GetServiceTypesRequest

 $element->set_GetServiceTypesRequest($data);
 $element->get_GetServiceTypesRequest();





=back


=head1 METHODS

=head2 new

 my $element = Shipment::GSO::WSDL::Elements::GetServiceTypes->new($data);

Constructor. The following data structure may be passed to new():

 {
   GetServiceTypesRequest =>  { # Shipment::GSO::WSDL::Types::GetServiceTypesRequest
     AccountNumber =>  $some_value, # int
   },
 },

=head1 AUTHOR

Generated by SOAP::WSDL

=cut

