
package Shipment::GSO::WSDL::Elements::GetShippingRate;
use strict;
use warnings;

{ # BLOCK to scope variables

sub get_xmlns { 'http://gso.com/GsoShipWS' }

__PACKAGE__->__set_name('GetShippingRate');
__PACKAGE__->__set_nillable();
__PACKAGE__->__set_minOccurs();
__PACKAGE__->__set_maxOccurs();
__PACKAGE__->__set_ref();

use base qw(
    SOAP::WSDL::XSD::Typelib::Element
    SOAP::WSDL::XSD::Typelib::ComplexType
);

our $XML_ATTRIBUTE_CLASS;
undef $XML_ATTRIBUTE_CLASS;

sub __get_attr_class {
    return $XML_ATTRIBUTE_CLASS;
}

use Class::Std::Fast::Storable constructor => 'none';
use base qw(SOAP::WSDL::XSD::Typelib::ComplexType);

Class::Std::initialize();

{ # BLOCK to scope variables

my %GetShippingRateRequest_of :ATTR(:get<GetShippingRateRequest>);

__PACKAGE__->_factory(
    [ qw(        GetShippingRateRequest

    ) ],
    {
        'GetShippingRateRequest' => \%GetShippingRateRequest_of,
    },
    {
        'GetShippingRateRequest' => 'Shipment::GSO::WSDL::Types::GetShippingRateRequest',
    },
    {

        'GetShippingRateRequest' => 'GetShippingRateRequest',
    }
);

} # end BLOCK






} # end of BLOCK



1;


=pod

=head1 NAME

Shipment::GSO::WSDL::Elements::GetShippingRate

=head1 DESCRIPTION

Perl data type class for the XML Schema defined element
GetShippingRate from the namespace http://gso.com/GsoShipWS.







=head1 PROPERTIES

The following properties may be accessed using get_PROPERTY / set_PROPERTY
methods:

=over

=item * GetShippingRateRequest

 $element->set_GetShippingRateRequest($data);
 $element->get_GetShippingRateRequest();





=back


=head1 METHODS

=head2 new

 my $element = Shipment::GSO::WSDL::Elements::GetShippingRate->new($data);

Constructor. The following data structure may be passed to new():

 {
   GetShippingRateRequest =>  { # Shipment::GSO::WSDL::Types::GetShippingRateRequest
     AccountNumber =>  $some_value, # int
     OriginZip =>  $some_value, # string
     DestinationZip =>  $some_value, # string
     PackageWeight =>  $some_value, # int
     ServiceCode =>  $some_value, # string
     DeclaredValue =>  $some_value, # decimal
     CODValue =>  $some_value, # decimal
   },
 },

=head1 AUTHOR

Generated by SOAP::WSDL

=cut

