
package Shipment::GSO::WSDL::Elements::GetShippingRatesAndTimes;
use strict;
use warnings;

{ # BLOCK to scope variables

sub get_xmlns { 'http://gso.com/GsoShipWS' }

__PACKAGE__->__set_name('GetShippingRatesAndTimes');
__PACKAGE__->__set_nillable();
__PACKAGE__->__set_minOccurs();
__PACKAGE__->__set_maxOccurs();
__PACKAGE__->__set_ref();

use base qw(
    SOAP::WSDL::XSD::Typelib::Element
    SOAP::WSDL::XSD::Typelib::ComplexType
);

our $XML_ATTRIBUTE_CLASS;
undef $XML_ATTRIBUTE_CLASS;

sub __get_attr_class {
    return $XML_ATTRIBUTE_CLASS;
}

use Class::Std::Fast::Storable constructor => 'none';
use base qw(SOAP::WSDL::XSD::Typelib::ComplexType);

Class::Std::initialize();

{ # BLOCK to scope variables

my %GetShippingRatesAndTimesRequest_of :ATTR(:get<GetShippingRatesAndTimesRequest>);

__PACKAGE__->_factory(
    [ qw(        GetShippingRatesAndTimesRequest

    ) ],
    {
        'GetShippingRatesAndTimesRequest' => \%GetShippingRatesAndTimesRequest_of,
    },
    {
        'GetShippingRatesAndTimesRequest' => 'Shipment::GSO::WSDL::Types::GetShippingRatesAndTimesRequest',
    },
    {

        'GetShippingRatesAndTimesRequest' => 'GetShippingRatesAndTimesRequest',
    }
);

} # end BLOCK






} # end of BLOCK



1;


=pod

=head1 NAME

Shipment::GSO::WSDL::Elements::GetShippingRatesAndTimes

=head1 DESCRIPTION

Perl data type class for the XML Schema defined element
GetShippingRatesAndTimes from the namespace http://gso.com/GsoShipWS.







=head1 PROPERTIES

The following properties may be accessed using get_PROPERTY / set_PROPERTY
methods:

=over

=item * GetShippingRatesAndTimesRequest

 $element->set_GetShippingRatesAndTimesRequest($data);
 $element->get_GetShippingRatesAndTimesRequest();





=back


=head1 METHODS

=head2 new

 my $element = Shipment::GSO::WSDL::Elements::GetShippingRatesAndTimes->new($data);

Constructor. The following data structure may be passed to new():

 {
   GetShippingRatesAndTimesRequest =>  { # Shipment::GSO::WSDL::Types::GetShippingRatesAndTimesRequest
     AccountNumber =>  $some_value, # int
     OriginZip =>  $some_value, # string
     DestinationZip =>  $some_value, # string
     PackageWeight =>  $some_value, # int
     DeclaredValue =>  $some_value, # decimal
     CODValue =>  $some_value, # decimal
     ShipDate =>  $some_value, # dateTime
     PickupService =>  $some_value, # int
   },
 },

=head1 AUTHOR

Generated by SOAP::WSDL

=cut

