
package Shipment::GSO::WSDL::Elements::GetServiceTypesResponse;
use strict;
use warnings;

{ # BLOCK to scope variables

sub get_xmlns { 'http://gso.com/GsoShipWS' }

__PACKAGE__->__set_name('GetServiceTypesResponse');
__PACKAGE__->__set_nillable();
__PACKAGE__->__set_minOccurs();
__PACKAGE__->__set_maxOccurs();
__PACKAGE__->__set_ref();

use base qw(
    SOAP::WSDL::XSD::Typelib::Element
    SOAP::WSDL::XSD::Typelib::ComplexType
);

our $XML_ATTRIBUTE_CLASS;
undef $XML_ATTRIBUTE_CLASS;

sub __get_attr_class {
    return $XML_ATTRIBUTE_CLASS;
}

use Class::Std::Fast::Storable constructor => 'none';
use base qw(SOAP::WSDL::XSD::Typelib::ComplexType);

Class::Std::initialize();

{ # BLOCK to scope variables

my %GetServiceTypesResult_of :ATTR(:get<GetServiceTypesResult>);

__PACKAGE__->_factory(
    [ qw(        GetServiceTypesResult

    ) ],
    {
        'GetServiceTypesResult' => \%GetServiceTypesResult_of,
    },
    {
        'GetServiceTypesResult' => 'Shipment::GSO::WSDL::Types::GetServiceTypesResult',
    },
    {

        'GetServiceTypesResult' => 'GetServiceTypesResult',
    }
);

} # end BLOCK






} # end of BLOCK



1;


=pod

=head1 NAME

Shipment::GSO::WSDL::Elements::GetServiceTypesResponse

=head1 DESCRIPTION

Perl data type class for the XML Schema defined element
GetServiceTypesResponse from the namespace http://gso.com/GsoShipWS.







=head1 PROPERTIES

The following properties may be accessed using get_PROPERTY / set_PROPERTY
methods:

=over

=item * GetServiceTypesResult

 $element->set_GetServiceTypesResult($data);
 $element->get_GetServiceTypesResult();





=back


=head1 METHODS

=head2 new

 my $element = Shipment::GSO::WSDL::Elements::GetServiceTypesResponse->new($data);

Constructor. The following data structure may be passed to new():

 {
   GetServiceTypesResult =>  { # Shipment::GSO::WSDL::Types::GetServiceTypesResult
     Service =>  { # Shipment::GSO::WSDL::Types::ArrayOfService
       Service =>  { # Shipment::GSO::WSDL::Types::Service
         Code =>  $some_value, # string
         Description =>  $some_value, # string
       },
     },
     Result =>  { # Shipment::GSO::WSDL::Types::Result
       Code =>  $some_value, # int
       Message =>  $some_value, # string
     },
   },
 },

=head1 AUTHOR

Generated by SOAP::WSDL

=cut

