
package Shipment::GSO::WSDL::Elements::SubmitOnCallPickup;
use strict;
use warnings;

{ # BLOCK to scope variables

sub get_xmlns { 'http://gso.com/GsoShipWS' }

__PACKAGE__->__set_name('SubmitOnCallPickup');
__PACKAGE__->__set_nillable();
__PACKAGE__->__set_minOccurs();
__PACKAGE__->__set_maxOccurs();
__PACKAGE__->__set_ref();

use base qw(
    SOAP::WSDL::XSD::Typelib::Element
    SOAP::WSDL::XSD::Typelib::ComplexType
);

our $XML_ATTRIBUTE_CLASS;
undef $XML_ATTRIBUTE_CLASS;

sub __get_attr_class {
    return $XML_ATTRIBUTE_CLASS;
}

use Class::Std::Fast::Storable constructor => 'none';
use base qw(SOAP::WSDL::XSD::Typelib::ComplexType);

Class::Std::initialize();

{ # BLOCK to scope variables

my %OnCallPickupRequest_of :ATTR(:get<OnCallPickupRequest>);

__PACKAGE__->_factory(
    [ qw(        OnCallPickupRequest

    ) ],
    {
        'OnCallPickupRequest' => \%OnCallPickupRequest_of,
    },
    {
        'OnCallPickupRequest' => 'Shipment::GSO::WSDL::Types::SubmitOnCallPickupRequest',
    },
    {

        'OnCallPickupRequest' => 'OnCallPickupRequest',
    }
);

} # end BLOCK






} # end of BLOCK



1;


=pod

=head1 NAME

Shipment::GSO::WSDL::Elements::SubmitOnCallPickup

=head1 DESCRIPTION

Perl data type class for the XML Schema defined element
SubmitOnCallPickup from the namespace http://gso.com/GsoShipWS.







=head1 PROPERTIES

The following properties may be accessed using get_PROPERTY / set_PROPERTY
methods:

=over

=item * OnCallPickupRequest

 $element->set_OnCallPickupRequest($data);
 $element->get_OnCallPickupRequest();





=back


=head1 METHODS

=head2 new

 my $element = Shipment::GSO::WSDL::Elements::SubmitOnCallPickup->new($data);

Constructor. The following data structure may be passed to new():

 {
   OnCallPickupRequest =>  { # Shipment::GSO::WSDL::Types::SubmitOnCallPickupRequest
     Pickup =>  { # Shipment::GSO::WSDL::Types::Pickup
       AccountNumber =>  $some_value, # int
       ShipperCompany =>  $some_value, # string
       ShipperContact =>  $some_value, # string
       ShipperPhone =>  $some_value, # string
       ShipperEmail =>  $some_value, # string
       PickupAddress1 =>  $some_value, # string
       PickupAddress2 =>  $some_value, # string
       PickupCity =>  $some_value, # string
       PickupState =>  $some_value, # string
       PickupZip =>  $some_value, # string
       PickupInstructions =>  $some_value, # string
       EarliestPickupTime =>  $some_value, # string
       LatestPickupTime =>  $some_value, # string
       PickupDate =>  $some_value, # dateTime
       PickupNotification =>  $some_value, # boolean
       NumPackages =>  $some_value, # int
       TotalWeight =>  $some_value, # int
     },
     AllowDuplicateRequest =>  $some_value, # boolean
   },
 },

=head1 AUTHOR

Generated by SOAP::WSDL

=cut

