
package Shipment::GSO::WSDL::Elements::SubmitOnCallPickupResponse;
use strict;
use warnings;

{ # BLOCK to scope variables

sub get_xmlns { 'http://gso.com/GsoShipWS' }

__PACKAGE__->__set_name('SubmitOnCallPickupResponse');
__PACKAGE__->__set_nillable();
__PACKAGE__->__set_minOccurs();
__PACKAGE__->__set_maxOccurs();
__PACKAGE__->__set_ref();

use base qw(
    SOAP::WSDL::XSD::Typelib::Element
    SOAP::WSDL::XSD::Typelib::ComplexType
);

our $XML_ATTRIBUTE_CLASS;
undef $XML_ATTRIBUTE_CLASS;

sub __get_attr_class {
    return $XML_ATTRIBUTE_CLASS;
}

use Class::Std::Fast::Storable constructor => 'none';
use base qw(SOAP::WSDL::XSD::Typelib::ComplexType);

Class::Std::initialize();

{ # BLOCK to scope variables

my %SubmitOnCallPickupResult_of :ATTR(:get<SubmitOnCallPickupResult>);

__PACKAGE__->_factory(
    [ qw(        SubmitOnCallPickupResult

    ) ],
    {
        'SubmitOnCallPickupResult' => \%SubmitOnCallPickupResult_of,
    },
    {
        'SubmitOnCallPickupResult' => 'Shipment::GSO::WSDL::Types::SubmitOnCallPickupResult',
    },
    {

        'SubmitOnCallPickupResult' => 'SubmitOnCallPickupResult',
    }
);

} # end BLOCK






} # end of BLOCK



1;


=pod

=head1 NAME

Shipment::GSO::WSDL::Elements::SubmitOnCallPickupResponse

=head1 DESCRIPTION

Perl data type class for the XML Schema defined element
SubmitOnCallPickupResponse from the namespace http://gso.com/GsoShipWS.







=head1 PROPERTIES

The following properties may be accessed using get_PROPERTY / set_PROPERTY
methods:

=over

=item * SubmitOnCallPickupResult

 $element->set_SubmitOnCallPickupResult($data);
 $element->get_SubmitOnCallPickupResult();





=back


=head1 METHODS

=head2 new

 my $element = Shipment::GSO::WSDL::Elements::SubmitOnCallPickupResponse->new($data);

Constructor. The following data structure may be passed to new():

 {
   SubmitOnCallPickupResult =>  { # Shipment::GSO::WSDL::Types::SubmitOnCallPickupResult
     OnCallPickupInfo =>  { # Shipment::GSO::WSDL::Types::OnCallPickupInfo
       ConfirmationNumber =>  $some_value, # int
     },
     Result =>  { # Shipment::GSO::WSDL::Types::Result
       Code =>  $some_value, # int
       Message =>  $some_value, # string
     },
   },
 },

=head1 AUTHOR

Generated by SOAP::WSDL

=cut

