
package Shipment::GSO::WSDL::Elements::SubmitShipment;
use strict;
use warnings;

{ # BLOCK to scope variables

sub get_xmlns { 'http://gso.com/GsoShipWS' }

__PACKAGE__->__set_name('SubmitShipment');
__PACKAGE__->__set_nillable();
__PACKAGE__->__set_minOccurs();
__PACKAGE__->__set_maxOccurs();
__PACKAGE__->__set_ref();

use base qw(
    SOAP::WSDL::XSD::Typelib::Element
    SOAP::WSDL::XSD::Typelib::ComplexType
);

our $XML_ATTRIBUTE_CLASS;
undef $XML_ATTRIBUTE_CLASS;

sub __get_attr_class {
    return $XML_ATTRIBUTE_CLASS;
}

use Class::Std::Fast::Storable constructor => 'none';
use base qw(SOAP::WSDL::XSD::Typelib::ComplexType);

Class::Std::initialize();

{ # BLOCK to scope variables

my %Shipment_of :ATTR(:get<Shipment>);

__PACKAGE__->_factory(
    [ qw(        Shipment

    ) ],
    {
        'Shipment' => \%Shipment_of,
    },
    {
        'Shipment' => 'Shipment::GSO::WSDL::Types::SubmitShipmentRequest',
    },
    {

        'Shipment' => 'Shipment',
    }
);

} # end BLOCK






} # end of BLOCK



1;


=pod

=head1 NAME

Shipment::GSO::WSDL::Elements::SubmitShipment

=head1 DESCRIPTION

Perl data type class for the XML Schema defined element
SubmitShipment from the namespace http://gso.com/GsoShipWS.







=head1 PROPERTIES

The following properties may be accessed using get_PROPERTY / set_PROPERTY
methods:

=over

=item * Shipment

 $element->set_Shipment($data);
 $element->get_Shipment();





=back


=head1 METHODS

=head2 new

 my $element = Shipment::GSO::WSDL::Elements::SubmitShipment->new($data);

Constructor. The following data structure may be passed to new():

 {
   Shipment =>  { # Shipment::GSO::WSDL::Types::SubmitShipmentRequest
     Package =>  { # Shipment::GSO::WSDL::Types::Package
       AccountNumber =>  $some_value, # int
       TrackingNumber =>  $some_value, # string
       ShipperCompany =>  $some_value, # string
       ShipperContact =>  $some_value, # string
       ShipperPhone =>  $some_value, # string
       ShipperEmail =>  $some_value, # string
       PickupAddress1 =>  $some_value, # string
       PickupAddress2 =>  $some_value, # string
       PickupCity =>  $some_value, # string
       PickupState =>  $some_value, # string
       PickupZip =>  $some_value, # string
       ShipToCompany =>  $some_value, # string
       ShipToAttention =>  $some_value, # string
       ShipToPhone =>  $some_value, # string
       ShipToEmail =>  $some_value, # string
       DeliveryAddress1 =>  $some_value, # string
       DeliveryAddress2 =>  $some_value, # string
       DeliveryCity =>  $some_value, # string
       DeliveryState =>  $some_value, # string
       DeliveryZip =>  $some_value, # string
       ServiceCode =>  $some_value, # string
       ShipmentReference =>  $some_value, # string
       DeclaredValue =>  $some_value, # decimal
       CODValue =>  $some_value, # decimal
       SpecialInstructions =>  $some_value, # string
       Weight =>  $some_value, # decimal
       SignatureCode => $some_value, # SignatureType
       AddnShipperReference1 =>  $some_value, # string
       AddnShipperReference2 =>  $some_value, # string
     },
     Notification =>  { # Shipment::GSO::WSDL::Types::Notification
       ShipmentNotification =>  $some_value, # string
       ExceptionNotification =>  $some_value, # string
       DeliveryNotification =>  $some_value, # string
       ReceiptNotification =>  $some_value, # string
       ShipmentNotificationComments =>  $some_value, # string
       ExceptionNotificationComments =>  $some_value, # string
       DeliveryNotificationComments =>  $some_value, # string
       ReceiptNotificationComments =>  $some_value, # string
     },
     ShipmentLabel =>  { # Shipment::GSO::WSDL::Types::ShipmentLabel
       Type => $some_value, # LabelType
     },
   },
 },

=head1 AUTHOR

Generated by SOAP::WSDL

=cut

