
package Shipment::GSO::WSDL::Elements::SubmitShipmentResponse;
use strict;
use warnings;

{ # BLOCK to scope variables

sub get_xmlns { 'http://gso.com/GsoShipWS' }

__PACKAGE__->__set_name('SubmitShipmentResponse');
__PACKAGE__->__set_nillable();
__PACKAGE__->__set_minOccurs();
__PACKAGE__->__set_maxOccurs();
__PACKAGE__->__set_ref();

use base qw(
    SOAP::WSDL::XSD::Typelib::Element
    SOAP::WSDL::XSD::Typelib::ComplexType
);

our $XML_ATTRIBUTE_CLASS;
undef $XML_ATTRIBUTE_CLASS;

sub __get_attr_class {
    return $XML_ATTRIBUTE_CLASS;
}

use Class::Std::Fast::Storable constructor => 'none';
use base qw(SOAP::WSDL::XSD::Typelib::ComplexType);

Class::Std::initialize();

{ # BLOCK to scope variables

my %SubmitShipmentResult_of :ATTR(:get<SubmitShipmentResult>);

__PACKAGE__->_factory(
    [ qw(        SubmitShipmentResult

    ) ],
    {
        'SubmitShipmentResult' => \%SubmitShipmentResult_of,
    },
    {
        'SubmitShipmentResult' => 'Shipment::GSO::WSDL::Types::SubmitShipmentResult',
    },
    {

        'SubmitShipmentResult' => 'SubmitShipmentResult',
    }
);

} # end BLOCK






} # end of BLOCK



1;


=pod

=head1 NAME

Shipment::GSO::WSDL::Elements::SubmitShipmentResponse

=head1 DESCRIPTION

Perl data type class for the XML Schema defined element
SubmitShipmentResponse from the namespace http://gso.com/GsoShipWS.







=head1 PROPERTIES

The following properties may be accessed using get_PROPERTY / set_PROPERTY
methods:

=over

=item * SubmitShipmentResult

 $element->set_SubmitShipmentResult($data);
 $element->get_SubmitShipmentResult();





=back


=head1 METHODS

=head2 new

 my $element = Shipment::GSO::WSDL::Elements::SubmitShipmentResponse->new($data);

Constructor. The following data structure may be passed to new():

 {
   SubmitShipmentResult =>  { # Shipment::GSO::WSDL::Types::SubmitShipmentResult
     SubmitShipmentInfo =>  { # Shipment::GSO::WSDL::Types::SubmitShipmentInfo
       AccountNumber =>  $some_value, # int
       TrackingNumber =>  $some_value, # string
     },
     ShipmentCharges =>  { # Shipment::GSO::WSDL::Types::ShipmentCharges
       TransportationCharge =>  $some_value, # decimal
       CODCharge =>  $some_value, # decimal
       InsuranceCharge =>  $some_value, # decimal
       OtherCharge =>  $some_value, # decimal
       FuelSurcharge =>  $some_value, # decimal
       TotalCharge =>  $some_value, # decimal
     },
     Label =>  { # Shipment::GSO::WSDL::Types::Label
       Paper =>  $some_value, # base64Binary
       Thermal =>  $some_value, # string
     },
     Result =>  { # Shipment::GSO::WSDL::Types::Result
       Code =>  $some_value, # int
       Message =>  $some_value, # string
     },
   },
 },

=head1 AUTHOR

Generated by SOAP::WSDL

=cut

