
package Shipment::GSO::WSDL::Elements::SubmitShippingSupplyOrder;
use strict;
use warnings;

{ # BLOCK to scope variables

sub get_xmlns { 'http://gso.com/GsoShipWS' }

__PACKAGE__->__set_name('SubmitShippingSupplyOrder');
__PACKAGE__->__set_nillable();
__PACKAGE__->__set_minOccurs();
__PACKAGE__->__set_maxOccurs();
__PACKAGE__->__set_ref();

use base qw(
    SOAP::WSDL::XSD::Typelib::Element
    SOAP::WSDL::XSD::Typelib::ComplexType
);

our $XML_ATTRIBUTE_CLASS;
undef $XML_ATTRIBUTE_CLASS;

sub __get_attr_class {
    return $XML_ATTRIBUTE_CLASS;
}

use Class::Std::Fast::Storable constructor => 'none';
use base qw(SOAP::WSDL::XSD::Typelib::ComplexType);

Class::Std::initialize();

{ # BLOCK to scope variables

my %ShippingSupplyOrderRequest_of :ATTR(:get<ShippingSupplyOrderRequest>);

__PACKAGE__->_factory(
    [ qw(        ShippingSupplyOrderRequest

    ) ],
    {
        'ShippingSupplyOrderRequest' => \%ShippingSupplyOrderRequest_of,
    },
    {
        'ShippingSupplyOrderRequest' => 'Shipment::GSO::WSDL::Types::SubmitShippingSupplyOrderRequest',
    },
    {

        'ShippingSupplyOrderRequest' => 'ShippingSupplyOrderRequest',
    }
);

} # end BLOCK






} # end of BLOCK



1;


=pod

=head1 NAME

Shipment::GSO::WSDL::Elements::SubmitShippingSupplyOrder

=head1 DESCRIPTION

Perl data type class for the XML Schema defined element
SubmitShippingSupplyOrder from the namespace http://gso.com/GsoShipWS.







=head1 PROPERTIES

The following properties may be accessed using get_PROPERTY / set_PROPERTY
methods:

=over

=item * ShippingSupplyOrderRequest

 $element->set_ShippingSupplyOrderRequest($data);
 $element->get_ShippingSupplyOrderRequest();





=back


=head1 METHODS

=head2 new

 my $element = Shipment::GSO::WSDL::Elements::SubmitShippingSupplyOrder->new($data);

Constructor. The following data structure may be passed to new():

 {
   ShippingSupplyOrderRequest =>  { # Shipment::GSO::WSDL::Types::SubmitShippingSupplyOrderRequest
     SupplyOrder =>  { # Shipment::GSO::WSDL::Types::SupplyOrder
       AccountNumber =>  $some_value, # int
       ShipToCompany =>  $some_value, # string
       ShipToAttention =>  $some_value, # string
       ShipToPhone =>  $some_value, # string
       ShipToEmail =>  $some_value, # string
       DeliveryAddress1 =>  $some_value, # string
       DeliveryAddress2 =>  $some_value, # string
       DeliveryCity =>  $some_value, # string
       DeliveryState =>  $some_value, # string
       DeliveryZip =>  $some_value, # string
       OrderNotes =>  $some_value, # string
       DeliveryNotes =>  $some_value, # string
     },
     SupplyItems =>  { # Shipment::GSO::WSDL::Types::ArrayOfSupplyItem
       SupplyItem =>  { # Shipment::GSO::WSDL::Types::SupplyItem
         Number =>  $some_value, # string
         Description =>  $some_value, # string
       },
     },
   },
 },

=head1 AUTHOR

Generated by SOAP::WSDL

=cut

