
package Shipment::GSO::WSDL::Elements::TrackShipment;
use strict;
use warnings;

{ # BLOCK to scope variables

sub get_xmlns { 'http://gso.com/GsoShipWS' }

__PACKAGE__->__set_name('TrackShipment');
__PACKAGE__->__set_nillable();
__PACKAGE__->__set_minOccurs();
__PACKAGE__->__set_maxOccurs();
__PACKAGE__->__set_ref();

use base qw(
    SOAP::WSDL::XSD::Typelib::Element
    SOAP::WSDL::XSD::Typelib::ComplexType
);

our $XML_ATTRIBUTE_CLASS;
undef $XML_ATTRIBUTE_CLASS;

sub __get_attr_class {
    return $XML_ATTRIBUTE_CLASS;
}

use Class::Std::Fast::Storable constructor => 'none';
use base qw(SOAP::WSDL::XSD::Typelib::ComplexType);

Class::Std::initialize();

{ # BLOCK to scope variables

my %TrackShipmentRequest_of :ATTR(:get<TrackShipmentRequest>);

__PACKAGE__->_factory(
    [ qw(        TrackShipmentRequest

    ) ],
    {
        'TrackShipmentRequest' => \%TrackShipmentRequest_of,
    },
    {
        'TrackShipmentRequest' => 'Shipment::GSO::WSDL::Types::TrackShipmentRequest',
    },
    {

        'TrackShipmentRequest' => 'TrackShipmentRequest',
    }
);

} # end BLOCK






} # end of BLOCK



1;


=pod

=head1 NAME

Shipment::GSO::WSDL::Elements::TrackShipment

=head1 DESCRIPTION

Perl data type class for the XML Schema defined element
TrackShipment from the namespace http://gso.com/GsoShipWS.







=head1 PROPERTIES

The following properties may be accessed using get_PROPERTY / set_PROPERTY
methods:

=over

=item * TrackShipmentRequest

 $element->set_TrackShipmentRequest($data);
 $element->get_TrackShipmentRequest();





=back


=head1 METHODS

=head2 new

 my $element = Shipment::GSO::WSDL::Elements::TrackShipment->new($data);

Constructor. The following data structure may be passed to new():

 {
   TrackShipmentRequest =>  { # Shipment::GSO::WSDL::Types::TrackShipmentRequest
     AccountNumber =>  $some_value, # int
     SearchType => $some_value, # ShipmentSearchType
     SearchValue =>  $some_value, # string
   },
 },

=head1 AUTHOR

Generated by SOAP::WSDL

=cut

