
package Shipment::GSO::WSDL::Elements::TrackShipmentResponse;
use strict;
use warnings;

{ # BLOCK to scope variables

sub get_xmlns { 'http://gso.com/GsoShipWS' }

__PACKAGE__->__set_name('TrackShipmentResponse');
__PACKAGE__->__set_nillable();
__PACKAGE__->__set_minOccurs();
__PACKAGE__->__set_maxOccurs();
__PACKAGE__->__set_ref();

use base qw(
    SOAP::WSDL::XSD::Typelib::Element
    SOAP::WSDL::XSD::Typelib::ComplexType
);

our $XML_ATTRIBUTE_CLASS;
undef $XML_ATTRIBUTE_CLASS;

sub __get_attr_class {
    return $XML_ATTRIBUTE_CLASS;
}

use Class::Std::Fast::Storable constructor => 'none';
use base qw(SOAP::WSDL::XSD::Typelib::ComplexType);

Class::Std::initialize();

{ # BLOCK to scope variables

my %TrackShipmentResult_of :ATTR(:get<TrackShipmentResult>);

__PACKAGE__->_factory(
    [ qw(        TrackShipmentResult

    ) ],
    {
        'TrackShipmentResult' => \%TrackShipmentResult_of,
    },
    {
        'TrackShipmentResult' => 'Shipment::GSO::WSDL::Types::TrackShipmentResult',
    },
    {

        'TrackShipmentResult' => 'TrackShipmentResult',
    }
);

} # end BLOCK






} # end of BLOCK



1;


=pod

=head1 NAME

Shipment::GSO::WSDL::Elements::TrackShipmentResponse

=head1 DESCRIPTION

Perl data type class for the XML Schema defined element
TrackShipmentResponse from the namespace http://gso.com/GsoShipWS.







=head1 PROPERTIES

The following properties may be accessed using get_PROPERTY / set_PROPERTY
methods:

=over

=item * TrackShipmentResult

 $element->set_TrackShipmentResult($data);
 $element->get_TrackShipmentResult();





=back


=head1 METHODS

=head2 new

 my $element = Shipment::GSO::WSDL::Elements::TrackShipmentResponse->new($data);

Constructor. The following data structure may be passed to new():

 {
   TrackShipmentResult =>  { # Shipment::GSO::WSDL::Types::TrackShipmentResult
     TrackShipmentInfo =>  { # Shipment::GSO::WSDL::Types::TrackShipmentInfo
       TrackingNumber =>  $some_value, # string
       ShipToCompany =>  $some_value, # string
       DeliveryCity =>  $some_value, # string
       DeliveryState =>  $some_value, # string
       DeliveryZip =>  $some_value, # string
       ServiceCode =>  $some_value, # string
       ShipmentReference =>  $some_value, # string
       Weight =>  $some_value, # int
     },
     Delivery =>  { # Shipment::GSO::WSDL::Types::Delivery
       ShipDate =>  $some_value, # dateTime
       ScheduledDate =>  $some_value, # dateTime
       DeliveryDate =>  $some_value, # dateTime
       TransitStatus =>  $some_value, # string
       DeliveryTime =>  $some_value, # string
       SignedBy =>  $some_value, # string
       Signature =>  $some_value, # base64Binary
     },
     TransitNotes =>  { # Shipment::GSO::WSDL::Types::ArrayOfTransitNote
       TransitNote =>  { # Shipment::GSO::WSDL::Types::TransitNote
         EventDate =>  $some_value, # dateTime
         Comments =>  $some_value, # string
       },
     },
     Result =>  { # Shipment::GSO::WSDL::Types::Result
       Code =>  $some_value, # int
       Message =>  $some_value, # string
     },
   },
 },

=head1 AUTHOR

Generated by SOAP::WSDL

=cut

