
package Shipment::GSO::WSDL::Elements::TrackShippingSupplyOrderResponse;
use strict;
use warnings;

{ # BLOCK to scope variables

sub get_xmlns { 'http://gso.com/GsoShipWS' }

__PACKAGE__->__set_name('TrackShippingSupplyOrderResponse');
__PACKAGE__->__set_nillable();
__PACKAGE__->__set_minOccurs();
__PACKAGE__->__set_maxOccurs();
__PACKAGE__->__set_ref();

use base qw(
    SOAP::WSDL::XSD::Typelib::Element
    SOAP::WSDL::XSD::Typelib::ComplexType
);

our $XML_ATTRIBUTE_CLASS;
undef $XML_ATTRIBUTE_CLASS;

sub __get_attr_class {
    return $XML_ATTRIBUTE_CLASS;
}

use Class::Std::Fast::Storable constructor => 'none';
use base qw(SOAP::WSDL::XSD::Typelib::ComplexType);

Class::Std::initialize();

{ # BLOCK to scope variables

my %TrackShippingSupplyOrderResult_of :ATTR(:get<TrackShippingSupplyOrderResult>);

__PACKAGE__->_factory(
    [ qw(        TrackShippingSupplyOrderResult

    ) ],
    {
        'TrackShippingSupplyOrderResult' => \%TrackShippingSupplyOrderResult_of,
    },
    {
        'TrackShippingSupplyOrderResult' => 'Shipment::GSO::WSDL::Types::TrackShippingSupplyOrderResult',
    },
    {

        'TrackShippingSupplyOrderResult' => 'TrackShippingSupplyOrderResult',
    }
);

} # end BLOCK






} # end of BLOCK



1;


=pod

=head1 NAME

Shipment::GSO::WSDL::Elements::TrackShippingSupplyOrderResponse

=head1 DESCRIPTION

Perl data type class for the XML Schema defined element
TrackShippingSupplyOrderResponse from the namespace http://gso.com/GsoShipWS.







=head1 PROPERTIES

The following properties may be accessed using get_PROPERTY / set_PROPERTY
methods:

=over

=item * TrackShippingSupplyOrderResult

 $element->set_TrackShippingSupplyOrderResult($data);
 $element->get_TrackShippingSupplyOrderResult();





=back


=head1 METHODS

=head2 new

 my $element = Shipment::GSO::WSDL::Elements::TrackShippingSupplyOrderResponse->new($data);

Constructor. The following data structure may be passed to new():

 {
   TrackShippingSupplyOrderResult =>  { # Shipment::GSO::WSDL::Types::TrackShippingSupplyOrderResult
     SupplyOrderInfo =>  { # Shipment::GSO::WSDL::Types::ArrayOfSupplyOrderInfo
       SupplyOrderInfo =>  { # Shipment::GSO::WSDL::Types::SupplyOrderInfo
         SupplyOrder =>  { # Shipment::GSO::WSDL::Types::SupplyOrder
           AccountNumber =>  $some_value, # int
           ShipToCompany =>  $some_value, # string
           ShipToAttention =>  $some_value, # string
           ShipToPhone =>  $some_value, # string
           ShipToEmail =>  $some_value, # string
           DeliveryAddress1 =>  $some_value, # string
           DeliveryAddress2 =>  $some_value, # string
           DeliveryCity =>  $some_value, # string
           DeliveryState =>  $some_value, # string
           DeliveryZip =>  $some_value, # string
           OrderNotes =>  $some_value, # string
           DeliveryNotes =>  $some_value, # string
         },
         SupplyOrderItems =>  { # Shipment::GSO::WSDL::Types::ArrayOfSupplyOrderItem
           SupplyOrderItem =>  { # Shipment::GSO::WSDL::Types::SupplyOrderItem
             Number =>  $some_value, # string
             Description =>  $some_value, # string
             Quantity =>  $some_value, # int
           },
         },
         TrackingInfo =>  { # Shipment::GSO::WSDL::Types::TrackingInfo
           OrderId =>  $some_value, # int
           OrderDate =>  $some_value, # dateTime
           OrderStatus =>  $some_value, # string
           ShipDate =>  $some_value, # dateTime
           TrackingNumber =>  $some_value, # string
         },
       },
     },
     Result =>  { # Shipment::GSO::WSDL::Types::Result
       Code =>  $some_value, # int
       Message =>  $some_value, # string
     },
   },
 },

=head1 AUTHOR

Generated by SOAP::WSDL

=cut

