
package Shipment::GSO::WSDL::Elements::VoidShipmentResponse;
use strict;
use warnings;

{ # BLOCK to scope variables

sub get_xmlns { 'http://gso.com/GsoShipWS' }

__PACKAGE__->__set_name('VoidShipmentResponse');
__PACKAGE__->__set_nillable();
__PACKAGE__->__set_minOccurs();
__PACKAGE__->__set_maxOccurs();
__PACKAGE__->__set_ref();

use base qw(
    SOAP::WSDL::XSD::Typelib::Element
    SOAP::WSDL::XSD::Typelib::ComplexType
);

our $XML_ATTRIBUTE_CLASS;
undef $XML_ATTRIBUTE_CLASS;

sub __get_attr_class {
    return $XML_ATTRIBUTE_CLASS;
}

use Class::Std::Fast::Storable constructor => 'none';
use base qw(SOAP::WSDL::XSD::Typelib::ComplexType);

Class::Std::initialize();

{ # BLOCK to scope variables

my %VoidShipmentResult_of :ATTR(:get<VoidShipmentResult>);

__PACKAGE__->_factory(
    [ qw(        VoidShipmentResult

    ) ],
    {
        'VoidShipmentResult' => \%VoidShipmentResult_of,
    },
    {
        'VoidShipmentResult' => 'Shipment::GSO::WSDL::Types::VoidShipmentResult',
    },
    {

        'VoidShipmentResult' => 'VoidShipmentResult',
    }
);

} # end BLOCK






} # end of BLOCK



1;


=pod

=head1 NAME

Shipment::GSO::WSDL::Elements::VoidShipmentResponse

=head1 DESCRIPTION

Perl data type class for the XML Schema defined element
VoidShipmentResponse from the namespace http://gso.com/GsoShipWS.







=head1 PROPERTIES

The following properties may be accessed using get_PROPERTY / set_PROPERTY
methods:

=over

=item * VoidShipmentResult

 $element->set_VoidShipmentResult($data);
 $element->get_VoidShipmentResult();





=back


=head1 METHODS

=head2 new

 my $element = Shipment::GSO::WSDL::Elements::VoidShipmentResponse->new($data);

Constructor. The following data structure may be passed to new():

 {
   VoidShipmentResult =>  { # Shipment::GSO::WSDL::Types::VoidShipmentResult
     VoidShipmentInfo =>  { # Shipment::GSO::WSDL::Types::VoidShipmentInfo
       AccountNumber =>  $some_value, # int
       TrackingNumber =>  $some_value, # string
     },
     Result =>  { # Shipment::GSO::WSDL::Types::Result
       Code =>  $some_value, # int
       Message =>  $some_value, # string
     },
   },
 },

=head1 AUTHOR

Generated by SOAP::WSDL

=cut

