package Shipment::GSO::WSDL::Types::ArrayOfTransitNote;
use strict;
use warnings;


__PACKAGE__->_set_element_form_qualified(1);

sub get_xmlns { 'http://gso.com/GsoShipWS' };

our $XML_ATTRIBUTE_CLASS;
undef $XML_ATTRIBUTE_CLASS;

sub __get_attr_class {
    return $XML_ATTRIBUTE_CLASS;
}

use Class::Std::Fast::Storable constructor => 'none';
use base qw(SOAP::WSDL::XSD::Typelib::ComplexType);

Class::Std::initialize();

{ # BLOCK to scope variables

my %TransitNote_of :ATTR(:get<TransitNote>);

__PACKAGE__->_factory(
    [ qw(        TransitNote

    ) ],
    {
        'TransitNote' => \%TransitNote_of,
    },
    {
        'TransitNote' => 'Shipment::GSO::WSDL::Types::TransitNote',
    },
    {

        'TransitNote' => 'TransitNote',
    }
);

} # end BLOCK







1;


=pod

=head1 NAME

Shipment::GSO::WSDL::Types::ArrayOfTransitNote

=head1 DESCRIPTION

Perl data type class for the XML Schema defined complexType
ArrayOfTransitNote from the namespace http://gso.com/GsoShipWS.






=head2 PROPERTIES

The following properties may be accessed using get_PROPERTY / set_PROPERTY
methods:

=over

=item * TransitNote




=back


=head1 METHODS

=head2 new

Constructor. The following data structure may be passed to new():

 { # Shipment::GSO::WSDL::Types::ArrayOfTransitNote
   TransitNote =>  { # Shipment::GSO::WSDL::Types::TransitNote
     EventDate =>  $some_value, # dateTime
     Comments =>  $some_value, # string
   },
 },




=head1 AUTHOR

Generated by SOAP::WSDL

=cut

