package Shipment::GSO::WSDL::Types::ArrayOfSupplyOrderItem;
use strict;
use warnings;


__PACKAGE__->_set_element_form_qualified(1);

sub get_xmlns { 'http://gso.com/GsoShipWS' };

our $XML_ATTRIBUTE_CLASS;
undef $XML_ATTRIBUTE_CLASS;

sub __get_attr_class {
    return $XML_ATTRIBUTE_CLASS;
}

use Class::Std::Fast::Storable constructor => 'none';
use base qw(SOAP::WSDL::XSD::Typelib::ComplexType);

Class::Std::initialize();

{ # BLOCK to scope variables

my %SupplyOrderItem_of :ATTR(:get<SupplyOrderItem>);

__PACKAGE__->_factory(
    [ qw(        SupplyOrderItem

    ) ],
    {
        'SupplyOrderItem' => \%SupplyOrderItem_of,
    },
    {
        'SupplyOrderItem' => 'Shipment::GSO::WSDL::Types::SupplyOrderItem',
    },
    {

        'SupplyOrderItem' => 'SupplyOrderItem',
    }
);

} # end BLOCK







1;


=pod

=head1 NAME

Shipment::GSO::WSDL::Types::ArrayOfSupplyOrderItem

=head1 DESCRIPTION

Perl data type class for the XML Schema defined complexType
ArrayOfSupplyOrderItem from the namespace http://gso.com/GsoShipWS.






=head2 PROPERTIES

The following properties may be accessed using get_PROPERTY / set_PROPERTY
methods:

=over

=item * SupplyOrderItem




=back


=head1 METHODS

=head2 new

Constructor. The following data structure may be passed to new():

 { # Shipment::GSO::WSDL::Types::ArrayOfSupplyOrderItem
   SupplyOrderItem =>  { # Shipment::GSO::WSDL::Types::SupplyOrderItem
     Number =>  $some_value, # string
     Description =>  $some_value, # string
     Quantity =>  $some_value, # int
   },
 },




=head1 AUTHOR

Generated by SOAP::WSDL

=cut

