package Shipment::GSO::WSDL::Types::ArrayOfService;
use strict;
use warnings;


__PACKAGE__->_set_element_form_qualified(1);

sub get_xmlns { 'http://gso.com/GsoShipWS' };

our $XML_ATTRIBUTE_CLASS;
undef $XML_ATTRIBUTE_CLASS;

sub __get_attr_class {
    return $XML_ATTRIBUTE_CLASS;
}

use Class::Std::Fast::Storable constructor => 'none';
use base qw(SOAP::WSDL::XSD::Typelib::ComplexType);

Class::Std::initialize();

{ # BLOCK to scope variables

my %Service_of :ATTR(:get<Service>);

__PACKAGE__->_factory(
    [ qw(        Service

    ) ],
    {
        'Service' => \%Service_of,
    },
    {
        'Service' => 'Shipment::GSO::WSDL::Types::Service',
    },
    {

        'Service' => 'Service',
    }
);

} # end BLOCK







1;


=pod

=head1 NAME

Shipment::GSO::WSDL::Types::ArrayOfService

=head1 DESCRIPTION

Perl data type class for the XML Schema defined complexType
ArrayOfService from the namespace http://gso.com/GsoShipWS.






=head2 PROPERTIES

The following properties may be accessed using get_PROPERTY / set_PROPERTY
methods:

=over

=item * Service




=back


=head1 METHODS

=head2 new

Constructor. The following data structure may be passed to new():

 { # Shipment::GSO::WSDL::Types::ArrayOfService
   Service =>  { # Shipment::GSO::WSDL::Types::Service
     Code =>  $some_value, # string
     Description =>  $some_value, # string
   },
 },




=head1 AUTHOR

Generated by SOAP::WSDL

=cut

