package Shipment::GSO::WSDL::Types::ArrayOfDeliveryTimesInfo;
use strict;
use warnings;


__PACKAGE__->_set_element_form_qualified(1);

sub get_xmlns { 'http://gso.com/GsoShipWS' };

our $XML_ATTRIBUTE_CLASS;
undef $XML_ATTRIBUTE_CLASS;

sub __get_attr_class {
    return $XML_ATTRIBUTE_CLASS;
}

use Class::Std::Fast::Storable constructor => 'none';
use base qw(SOAP::WSDL::XSD::Typelib::ComplexType);

Class::Std::initialize();

{ # BLOCK to scope variables

my %DeliveryTimesInfo_of :ATTR(:get<DeliveryTimesInfo>);

__PACKAGE__->_factory(
    [ qw(        DeliveryTimesInfo

    ) ],
    {
        'DeliveryTimesInfo' => \%DeliveryTimesInfo_of,
    },
    {
        'DeliveryTimesInfo' => 'Shipment::GSO::WSDL::Types::DeliveryTimesInfo',
    },
    {

        'DeliveryTimesInfo' => 'DeliveryTimesInfo',
    }
);

} # end BLOCK







1;


=pod

=head1 NAME

Shipment::GSO::WSDL::Types::ArrayOfDeliveryTimesInfo

=head1 DESCRIPTION

Perl data type class for the XML Schema defined complexType
ArrayOfDeliveryTimesInfo from the namespace http://gso.com/GsoShipWS.






=head2 PROPERTIES

The following properties may be accessed using get_PROPERTY / set_PROPERTY
methods:

=over

=item * DeliveryTimesInfo




=back


=head1 METHODS

=head2 new

Constructor. The following data structure may be passed to new():

 { # Shipment::GSO::WSDL::Types::ArrayOfDeliveryTimesInfo
   DeliveryTimesInfo =>  { # Shipment::GSO::WSDL::Types::DeliveryTimesInfo
     DeliveryLocation =>  { # Shipment::GSO::WSDL::Types::DeliveryLocation
       City =>  $some_value, # string
       ZipCode =>  $some_value, # string
     },
     DeliveryTimes =>  { # Shipment::GSO::WSDL::Types::ArrayOfDeliveryTime
       DeliveryTime =>  { # Shipment::GSO::WSDL::Types::DeliveryTime
         ServiceCode =>  $some_value, # string
         ServiceDescription =>  $some_value, # string
         GuaranteedDeliveryTime =>  $some_value, # string
       },
     },
   },
 },




=head1 AUTHOR

Generated by SOAP::WSDL

=cut

