package Shipment::GSO::WSDL::Types::DeliveryService;
use strict;
use warnings;


__PACKAGE__->_set_element_form_qualified(1);

sub get_xmlns { 'http://gso.com/GsoShipWS' };

our $XML_ATTRIBUTE_CLASS;
undef $XML_ATTRIBUTE_CLASS;

sub __get_attr_class {
    return $XML_ATTRIBUTE_CLASS;
}

use Class::Std::Fast::Storable constructor => 'none';
use base qw(SOAP::WSDL::XSD::Typelib::ComplexType);

Class::Std::initialize();

{ # BLOCK to scope variables

my %ServiceCode_of :ATTR(:get<ServiceCode>);
my %ServiceDescription_of :ATTR(:get<ServiceDescription>);
my %GuaranteedDeliveryDateTime_of :ATTR(:get<GuaranteedDeliveryDateTime>);
my %ShipmentCharges_of :ATTR(:get<ShipmentCharges>);

__PACKAGE__->_factory(
    [ qw(        ServiceCode
        ServiceDescription
        GuaranteedDeliveryDateTime
        ShipmentCharges

    ) ],
    {
        'ServiceCode' => \%ServiceCode_of,
        'ServiceDescription' => \%ServiceDescription_of,
        'GuaranteedDeliveryDateTime' => \%GuaranteedDeliveryDateTime_of,
        'ShipmentCharges' => \%ShipmentCharges_of,
    },
    {
        'ServiceCode' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
        'ServiceDescription' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
        'GuaranteedDeliveryDateTime' => 'SOAP::WSDL::XSD::Typelib::Builtin::dateTime',
        'ShipmentCharges' => 'Shipment::GSO::WSDL::Types::ShipmentCharges',
    },
    {

        'ServiceCode' => 'ServiceCode',
        'ServiceDescription' => 'ServiceDescription',
        'GuaranteedDeliveryDateTime' => 'GuaranteedDeliveryDateTime',
        'ShipmentCharges' => 'ShipmentCharges',
    }
);

} # end BLOCK







1;


=pod

=head1 NAME

Shipment::GSO::WSDL::Types::DeliveryService

=head1 DESCRIPTION

Perl data type class for the XML Schema defined complexType
DeliveryService from the namespace http://gso.com/GsoShipWS.






=head2 PROPERTIES

The following properties may be accessed using get_PROPERTY / set_PROPERTY
methods:

=over

=item * ServiceCode


=item * ServiceDescription


=item * GuaranteedDeliveryDateTime


=item * ShipmentCharges




=back


=head1 METHODS

=head2 new

Constructor. The following data structure may be passed to new():

 { # Shipment::GSO::WSDL::Types::DeliveryService
   ServiceCode =>  $some_value, # string
   ServiceDescription =>  $some_value, # string
   GuaranteedDeliveryDateTime =>  $some_value, # dateTime
   ShipmentCharges =>  { # Shipment::GSO::WSDL::Types::ShipmentCharges
     TransportationCharge =>  $some_value, # decimal
     CODCharge =>  $some_value, # decimal
     InsuranceCharge =>  $some_value, # decimal
     OtherCharge =>  $some_value, # decimal
     FuelSurcharge =>  $some_value, # decimal
     TotalCharge =>  $some_value, # decimal
   },
 },




=head1 AUTHOR

Generated by SOAP::WSDL

=cut

