package Shipment::GSO::WSDL::Types::DeliveryTime;
use strict;
use warnings;


__PACKAGE__->_set_element_form_qualified(1);

sub get_xmlns { 'http://gso.com/GsoShipWS' };

our $XML_ATTRIBUTE_CLASS;
undef $XML_ATTRIBUTE_CLASS;

sub __get_attr_class {
    return $XML_ATTRIBUTE_CLASS;
}

use Class::Std::Fast::Storable constructor => 'none';
use base qw(SOAP::WSDL::XSD::Typelib::ComplexType);

Class::Std::initialize();

{ # BLOCK to scope variables

my %ServiceCode_of :ATTR(:get<ServiceCode>);
my %ServiceDescription_of :ATTR(:get<ServiceDescription>);
my %GuaranteedDeliveryTime_of :ATTR(:get<GuaranteedDeliveryTime>);

__PACKAGE__->_factory(
    [ qw(        ServiceCode
        ServiceDescription
        GuaranteedDeliveryTime

    ) ],
    {
        'ServiceCode' => \%ServiceCode_of,
        'ServiceDescription' => \%ServiceDescription_of,
        'GuaranteedDeliveryTime' => \%GuaranteedDeliveryTime_of,
    },
    {
        'ServiceCode' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
        'ServiceDescription' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
        'GuaranteedDeliveryTime' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
    },
    {

        'ServiceCode' => 'ServiceCode',
        'ServiceDescription' => 'ServiceDescription',
        'GuaranteedDeliveryTime' => 'GuaranteedDeliveryTime',
    }
);

} # end BLOCK







1;


=pod

=head1 NAME

Shipment::GSO::WSDL::Types::DeliveryTime

=head1 DESCRIPTION

Perl data type class for the XML Schema defined complexType
DeliveryTime from the namespace http://gso.com/GsoShipWS.






=head2 PROPERTIES

The following properties may be accessed using get_PROPERTY / set_PROPERTY
methods:

=over

=item * ServiceCode


=item * ServiceDescription


=item * GuaranteedDeliveryTime




=back


=head1 METHODS

=head2 new

Constructor. The following data structure may be passed to new():

 { # Shipment::GSO::WSDL::Types::DeliveryTime
   ServiceCode =>  $some_value, # string
   ServiceDescription =>  $some_value, # string
   GuaranteedDeliveryTime =>  $some_value, # string
 },




=head1 AUTHOR

Generated by SOAP::WSDL

=cut

