package Shipment::GSO::WSDL::Types::Delivery;
use strict;
use warnings;


__PACKAGE__->_set_element_form_qualified(1);

sub get_xmlns { 'http://gso.com/GsoShipWS' };

our $XML_ATTRIBUTE_CLASS;
undef $XML_ATTRIBUTE_CLASS;

sub __get_attr_class {
    return $XML_ATTRIBUTE_CLASS;
}

use Class::Std::Fast::Storable constructor => 'none';
use base qw(SOAP::WSDL::XSD::Typelib::ComplexType);

Class::Std::initialize();

{ # BLOCK to scope variables

my %ShipDate_of :ATTR(:get<ShipDate>);
my %ScheduledDate_of :ATTR(:get<ScheduledDate>);
my %DeliveryDate_of :ATTR(:get<DeliveryDate>);
my %TransitStatus_of :ATTR(:get<TransitStatus>);
my %DeliveryTime_of :ATTR(:get<DeliveryTime>);
my %SignedBy_of :ATTR(:get<SignedBy>);
my %Signature_of :ATTR(:get<Signature>);

__PACKAGE__->_factory(
    [ qw(        ShipDate
        ScheduledDate
        DeliveryDate
        TransitStatus
        DeliveryTime
        SignedBy
        Signature

    ) ],
    {
        'ShipDate' => \%ShipDate_of,
        'ScheduledDate' => \%ScheduledDate_of,
        'DeliveryDate' => \%DeliveryDate_of,
        'TransitStatus' => \%TransitStatus_of,
        'DeliveryTime' => \%DeliveryTime_of,
        'SignedBy' => \%SignedBy_of,
        'Signature' => \%Signature_of,
    },
    {
        'ShipDate' => 'SOAP::WSDL::XSD::Typelib::Builtin::dateTime',
        'ScheduledDate' => 'SOAP::WSDL::XSD::Typelib::Builtin::dateTime',
        'DeliveryDate' => 'SOAP::WSDL::XSD::Typelib::Builtin::dateTime',
        'TransitStatus' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
        'DeliveryTime' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
        'SignedBy' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
        'Signature' => 'SOAP::WSDL::XSD::Typelib::Builtin::base64Binary',
    },
    {

        'ShipDate' => 'ShipDate',
        'ScheduledDate' => 'ScheduledDate',
        'DeliveryDate' => 'DeliveryDate',
        'TransitStatus' => 'TransitStatus',
        'DeliveryTime' => 'DeliveryTime',
        'SignedBy' => 'SignedBy',
        'Signature' => 'Signature',
    }
);

} # end BLOCK







1;


=pod

=head1 NAME

Shipment::GSO::WSDL::Types::Delivery

=head1 DESCRIPTION

Perl data type class for the XML Schema defined complexType
Delivery from the namespace http://gso.com/GsoShipWS.






=head2 PROPERTIES

The following properties may be accessed using get_PROPERTY / set_PROPERTY
methods:

=over

=item * ShipDate


=item * ScheduledDate


=item * DeliveryDate


=item * TransitStatus


=item * DeliveryTime


=item * SignedBy


=item * Signature




=back


=head1 METHODS

=head2 new

Constructor. The following data structure may be passed to new():

 { # Shipment::GSO::WSDL::Types::Delivery
   ShipDate =>  $some_value, # dateTime
   ScheduledDate =>  $some_value, # dateTime
   DeliveryDate =>  $some_value, # dateTime
   TransitStatus =>  $some_value, # string
   DeliveryTime =>  $some_value, # string
   SignedBy =>  $some_value, # string
   Signature =>  $some_value, # base64Binary
 },




=head1 AUTHOR

Generated by SOAP::WSDL

=cut

