package Shipment::GSO::WSDL::Types::GetDropBoxInfoResult;
use strict;
use warnings;


__PACKAGE__->_set_element_form_qualified(1);

sub get_xmlns { 'http://gso.com/GsoShipWS' };

our $XML_ATTRIBUTE_CLASS;
undef $XML_ATTRIBUTE_CLASS;

sub __get_attr_class {
    return $XML_ATTRIBUTE_CLASS;
}

use Class::Std::Fast::Storable constructor => 'none';
use base qw(SOAP::WSDL::XSD::Typelib::ComplexType);

Class::Std::initialize();

{ # BLOCK to scope variables

my %DropBoxInfo_of :ATTR(:get<DropBoxInfo>);
my %Result_of :ATTR(:get<Result>);

__PACKAGE__->_factory(
    [ qw(        DropBoxInfo
        Result

    ) ],
    {
        'DropBoxInfo' => \%DropBoxInfo_of,
        'Result' => \%Result_of,
    },
    {
        'DropBoxInfo' => 'Shipment::GSO::WSDL::Types::ArrayOfDropBoxInfo',
        'Result' => 'Shipment::GSO::WSDL::Types::Result',
    },
    {

        'DropBoxInfo' => 'DropBoxInfo',
        'Result' => 'Result',
    }
);

} # end BLOCK







1;


=pod

=head1 NAME

Shipment::GSO::WSDL::Types::GetDropBoxInfoResult

=head1 DESCRIPTION

Perl data type class for the XML Schema defined complexType
GetDropBoxInfoResult from the namespace http://gso.com/GsoShipWS.






=head2 PROPERTIES

The following properties may be accessed using get_PROPERTY / set_PROPERTY
methods:

=over

=item * DropBoxInfo


=item * Result




=back


=head1 METHODS

=head2 new

Constructor. The following data structure may be passed to new():

 { # Shipment::GSO::WSDL::Types::GetDropBoxInfoResult
   DropBoxInfo =>  { # Shipment::GSO::WSDL::Types::ArrayOfDropBoxInfo
     DropBoxInfo =>  { # Shipment::GSO::WSDL::Types::DropBoxInfo
       Address =>  $some_value, # string
       City =>  $some_value, # string
       Zip =>  $some_value, # string
       Notes =>  $some_value, # string
       EstimatedPickupTime =>  $some_value, # string
     },
   },
   Result =>  { # Shipment::GSO::WSDL::Types::Result
     Code =>  $some_value, # int
     Message =>  $some_value, # string
   },
 },




=head1 AUTHOR

Generated by SOAP::WSDL

=cut

