package Shipment::GSO::WSDL::Types::GetDropBoxInfoRequest;
use strict;
use warnings;


__PACKAGE__->_set_element_form_qualified(1);

sub get_xmlns { 'http://gso.com/GsoShipWS' };

our $XML_ATTRIBUTE_CLASS;
undef $XML_ATTRIBUTE_CLASS;

sub __get_attr_class {
    return $XML_ATTRIBUTE_CLASS;
}

use Class::Std::Fast::Storable constructor => 'none';
use base qw(SOAP::WSDL::XSD::Typelib::ComplexType);

Class::Std::initialize();

{ # BLOCK to scope variables

my %Address_of :ATTR(:get<Address>);
my %City_of :ATTR(:get<City>);
my %State_of :ATTR(:get<State>);
my %Zip_of :ATTR(:get<Zip>);

__PACKAGE__->_factory(
    [ qw(        Address
        City
        State
        Zip

    ) ],
    {
        'Address' => \%Address_of,
        'City' => \%City_of,
        'State' => \%State_of,
        'Zip' => \%Zip_of,
    },
    {
        'Address' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
        'City' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
        'State' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
        'Zip' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
    },
    {

        'Address' => 'Address',
        'City' => 'City',
        'State' => 'State',
        'Zip' => 'Zip',
    }
);

} # end BLOCK







1;


=pod

=head1 NAME

Shipment::GSO::WSDL::Types::GetDropBoxInfoRequest

=head1 DESCRIPTION

Perl data type class for the XML Schema defined complexType
GetDropBoxInfoRequest from the namespace http://gso.com/GsoShipWS.






=head2 PROPERTIES

The following properties may be accessed using get_PROPERTY / set_PROPERTY
methods:

=over

=item * Address


=item * City


=item * State


=item * Zip




=back


=head1 METHODS

=head2 new

Constructor. The following data structure may be passed to new():

 { # Shipment::GSO::WSDL::Types::GetDropBoxInfoRequest
   Address =>  $some_value, # string
   City =>  $some_value, # string
   State =>  $some_value, # string
   Zip =>  $some_value, # string
 },




=head1 AUTHOR

Generated by SOAP::WSDL

=cut

