package Shipment::GSO::WSDL::Types::Label;
use strict;
use warnings;


__PACKAGE__->_set_element_form_qualified(1);

sub get_xmlns { 'http://gso.com/GsoShipWS' };

our $XML_ATTRIBUTE_CLASS;
undef $XML_ATTRIBUTE_CLASS;

sub __get_attr_class {
    return $XML_ATTRIBUTE_CLASS;
}

use Class::Std::Fast::Storable constructor => 'none';
use base qw(SOAP::WSDL::XSD::Typelib::ComplexType);

Class::Std::initialize();

{ # BLOCK to scope variables

my %Paper_of :ATTR(:get<Paper>);
my %Thermal_of :ATTR(:get<Thermal>);

__PACKAGE__->_factory(
    [ qw(        Paper
        Thermal

    ) ],
    {
        'Paper' => \%Paper_of,
        'Thermal' => \%Thermal_of,
    },
    {
        'Paper' => 'SOAP::WSDL::XSD::Typelib::Builtin::base64Binary',
        'Thermal' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
    },
    {

        'Paper' => 'Paper',
        'Thermal' => 'Thermal',
    }
);

} # end BLOCK







1;


=pod

=head1 NAME

Shipment::GSO::WSDL::Types::Label

=head1 DESCRIPTION

Perl data type class for the XML Schema defined complexType
Label from the namespace http://gso.com/GsoShipWS.






=head2 PROPERTIES

The following properties may be accessed using get_PROPERTY / set_PROPERTY
methods:

=over

=item * Paper


=item * Thermal




=back


=head1 METHODS

=head2 new

Constructor. The following data structure may be passed to new():

 { # Shipment::GSO::WSDL::Types::Label
   Paper =>  $some_value, # base64Binary
   Thermal =>  $some_value, # string
 },




=head1 AUTHOR

Generated by SOAP::WSDL

=cut

