package Shipment::GSO::WSDL::Types::Notification;
use strict;
use warnings;


__PACKAGE__->_set_element_form_qualified(1);

sub get_xmlns { 'http://gso.com/GsoShipWS' };

our $XML_ATTRIBUTE_CLASS;
undef $XML_ATTRIBUTE_CLASS;

sub __get_attr_class {
    return $XML_ATTRIBUTE_CLASS;
}

use Class::Std::Fast::Storable constructor => 'none';
use base qw(SOAP::WSDL::XSD::Typelib::ComplexType);

Class::Std::initialize();

{ # BLOCK to scope variables

my %ShipmentNotification_of :ATTR(:get<ShipmentNotification>);
my %ExceptionNotification_of :ATTR(:get<ExceptionNotification>);
my %DeliveryNotification_of :ATTR(:get<DeliveryNotification>);
my %ReceiptNotification_of :ATTR(:get<ReceiptNotification>);
my %ShipmentNotificationComments_of :ATTR(:get<ShipmentNotificationComments>);
my %ExceptionNotificationComments_of :ATTR(:get<ExceptionNotificationComments>);
my %DeliveryNotificationComments_of :ATTR(:get<DeliveryNotificationComments>);
my %ReceiptNotificationComments_of :ATTR(:get<ReceiptNotificationComments>);

__PACKAGE__->_factory(
    [ qw(        ShipmentNotification
        ExceptionNotification
        DeliveryNotification
        ReceiptNotification
        ShipmentNotificationComments
        ExceptionNotificationComments
        DeliveryNotificationComments
        ReceiptNotificationComments

    ) ],
    {
        'ShipmentNotification' => \%ShipmentNotification_of,
        'ExceptionNotification' => \%ExceptionNotification_of,
        'DeliveryNotification' => \%DeliveryNotification_of,
        'ReceiptNotification' => \%ReceiptNotification_of,
        'ShipmentNotificationComments' => \%ShipmentNotificationComments_of,
        'ExceptionNotificationComments' => \%ExceptionNotificationComments_of,
        'DeliveryNotificationComments' => \%DeliveryNotificationComments_of,
        'ReceiptNotificationComments' => \%ReceiptNotificationComments_of,
    },
    {
        'ShipmentNotification' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
        'ExceptionNotification' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
        'DeliveryNotification' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
        'ReceiptNotification' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
        'ShipmentNotificationComments' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
        'ExceptionNotificationComments' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
        'DeliveryNotificationComments' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
        'ReceiptNotificationComments' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
    },
    {

        'ShipmentNotification' => 'ShipmentNotification',
        'ExceptionNotification' => 'ExceptionNotification',
        'DeliveryNotification' => 'DeliveryNotification',
        'ReceiptNotification' => 'ReceiptNotification',
        'ShipmentNotificationComments' => 'ShipmentNotificationComments',
        'ExceptionNotificationComments' => 'ExceptionNotificationComments',
        'DeliveryNotificationComments' => 'DeliveryNotificationComments',
        'ReceiptNotificationComments' => 'ReceiptNotificationComments',
    }
);

} # end BLOCK







1;


=pod

=head1 NAME

Shipment::GSO::WSDL::Types::Notification

=head1 DESCRIPTION

Perl data type class for the XML Schema defined complexType
Notification from the namespace http://gso.com/GsoShipWS.






=head2 PROPERTIES

The following properties may be accessed using get_PROPERTY / set_PROPERTY
methods:

=over

=item * ShipmentNotification


=item * ExceptionNotification


=item * DeliveryNotification


=item * ReceiptNotification


=item * ShipmentNotificationComments


=item * ExceptionNotificationComments


=item * DeliveryNotificationComments


=item * ReceiptNotificationComments




=back


=head1 METHODS

=head2 new

Constructor. The following data structure may be passed to new():

 { # Shipment::GSO::WSDL::Types::Notification
   ShipmentNotification =>  $some_value, # string
   ExceptionNotification =>  $some_value, # string
   DeliveryNotification =>  $some_value, # string
   ReceiptNotification =>  $some_value, # string
   ShipmentNotificationComments =>  $some_value, # string
   ExceptionNotificationComments =>  $some_value, # string
   DeliveryNotificationComments =>  $some_value, # string
   ReceiptNotificationComments =>  $some_value, # string
 },




=head1 AUTHOR

Generated by SOAP::WSDL

=cut

