package Shipment::GSO::WSDL::Types::ShipmentCharges;
use strict;
use warnings;


__PACKAGE__->_set_element_form_qualified(1);

sub get_xmlns { 'http://gso.com/GsoShipWS' };

our $XML_ATTRIBUTE_CLASS;
undef $XML_ATTRIBUTE_CLASS;

sub __get_attr_class {
    return $XML_ATTRIBUTE_CLASS;
}

use Class::Std::Fast::Storable constructor => 'none';
use base qw(SOAP::WSDL::XSD::Typelib::ComplexType);

Class::Std::initialize();

{ # BLOCK to scope variables

my %TransportationCharge_of :ATTR(:get<TransportationCharge>);
my %CODCharge_of :ATTR(:get<CODCharge>);
my %InsuranceCharge_of :ATTR(:get<InsuranceCharge>);
my %OtherCharge_of :ATTR(:get<OtherCharge>);
my %FuelSurcharge_of :ATTR(:get<FuelSurcharge>);
my %TotalCharge_of :ATTR(:get<TotalCharge>);

__PACKAGE__->_factory(
    [ qw(        TransportationCharge
        CODCharge
        InsuranceCharge
        OtherCharge
        FuelSurcharge
        TotalCharge

    ) ],
    {
        'TransportationCharge' => \%TransportationCharge_of,
        'CODCharge' => \%CODCharge_of,
        'InsuranceCharge' => \%InsuranceCharge_of,
        'OtherCharge' => \%OtherCharge_of,
        'FuelSurcharge' => \%FuelSurcharge_of,
        'TotalCharge' => \%TotalCharge_of,
    },
    {
        'TransportationCharge' => 'SOAP::WSDL::XSD::Typelib::Builtin::decimal',
        'CODCharge' => 'SOAP::WSDL::XSD::Typelib::Builtin::decimal',
        'InsuranceCharge' => 'SOAP::WSDL::XSD::Typelib::Builtin::decimal',
        'OtherCharge' => 'SOAP::WSDL::XSD::Typelib::Builtin::decimal',
        'FuelSurcharge' => 'SOAP::WSDL::XSD::Typelib::Builtin::decimal',
        'TotalCharge' => 'SOAP::WSDL::XSD::Typelib::Builtin::decimal',
    },
    {

        'TransportationCharge' => 'TransportationCharge',
        'CODCharge' => 'CODCharge',
        'InsuranceCharge' => 'InsuranceCharge',
        'OtherCharge' => 'OtherCharge',
        'FuelSurcharge' => 'FuelSurcharge',
        'TotalCharge' => 'TotalCharge',
    }
);

} # end BLOCK







1;


=pod

=head1 NAME

Shipment::GSO::WSDL::Types::ShipmentCharges

=head1 DESCRIPTION

Perl data type class for the XML Schema defined complexType
ShipmentCharges from the namespace http://gso.com/GsoShipWS.






=head2 PROPERTIES

The following properties may be accessed using get_PROPERTY / set_PROPERTY
methods:

=over

=item * TransportationCharge


=item * CODCharge


=item * InsuranceCharge


=item * OtherCharge


=item * FuelSurcharge


=item * TotalCharge




=back


=head1 METHODS

=head2 new

Constructor. The following data structure may be passed to new():

 { # Shipment::GSO::WSDL::Types::ShipmentCharges
   TransportationCharge =>  $some_value, # decimal
   CODCharge =>  $some_value, # decimal
   InsuranceCharge =>  $some_value, # decimal
   OtherCharge =>  $some_value, # decimal
   FuelSurcharge =>  $some_value, # decimal
   TotalCharge =>  $some_value, # decimal
 },




=head1 AUTHOR

Generated by SOAP::WSDL

=cut

