package Shipment::GSO::WSDL::Types::ShipmentLabel;
use strict;
use warnings;


__PACKAGE__->_set_element_form_qualified(1);

sub get_xmlns { 'http://gso.com/GsoShipWS' };

our $XML_ATTRIBUTE_CLASS;
undef $XML_ATTRIBUTE_CLASS;

sub __get_attr_class {
    return $XML_ATTRIBUTE_CLASS;
}

use Class::Std::Fast::Storable constructor => 'none';
use base qw(SOAP::WSDL::XSD::Typelib::ComplexType);

Class::Std::initialize();

{ # BLOCK to scope variables

my %Type_of :ATTR(:get<Type>);

__PACKAGE__->_factory(
    [ qw(        Type

    ) ],
    {
        'Type' => \%Type_of,
    },
    {
        'Type' => 'Shipment::GSO::WSDL::Types::LabelType',
    },
    {

        'Type' => 'Type',
    }
);

} # end BLOCK







1;


=pod

=head1 NAME

Shipment::GSO::WSDL::Types::ShipmentLabel

=head1 DESCRIPTION

Perl data type class for the XML Schema defined complexType
ShipmentLabel from the namespace http://gso.com/GsoShipWS.






=head2 PROPERTIES

The following properties may be accessed using get_PROPERTY / set_PROPERTY
methods:

=over

=item * Type




=back


=head1 METHODS

=head2 new

Constructor. The following data structure may be passed to new():

 { # Shipment::GSO::WSDL::Types::ShipmentLabel
   Type => $some_value, # LabelType
 },




=head1 AUTHOR

Generated by SOAP::WSDL

=cut

