package Shipment::GSO::WSDL::Types::SubmitShipmentRequest;
use strict;
use warnings;


__PACKAGE__->_set_element_form_qualified(1);

sub get_xmlns { 'http://gso.com/GsoShipWS' };

our $XML_ATTRIBUTE_CLASS;
undef $XML_ATTRIBUTE_CLASS;

sub __get_attr_class {
    return $XML_ATTRIBUTE_CLASS;
}

use Class::Std::Fast::Storable constructor => 'none';
use base qw(SOAP::WSDL::XSD::Typelib::ComplexType);

Class::Std::initialize();

{ # BLOCK to scope variables

my %Package_of :ATTR(:get<Package>);
my %Notification_of :ATTR(:get<Notification>);
my %ShipmentLabel_of :ATTR(:get<ShipmentLabel>);

__PACKAGE__->_factory(
    [ qw(        Package
        Notification
        ShipmentLabel

    ) ],
    {
        'Package' => \%Package_of,
        'Notification' => \%Notification_of,
        'ShipmentLabel' => \%ShipmentLabel_of,
    },
    {
        'Package' => 'Shipment::GSO::WSDL::Types::Package',
        'Notification' => 'Shipment::GSO::WSDL::Types::Notification',
        'ShipmentLabel' => 'Shipment::GSO::WSDL::Types::ShipmentLabel',
    },
    {

        'Package' => 'Package',
        'Notification' => 'Notification',
        'ShipmentLabel' => 'ShipmentLabel',
    }
);

} # end BLOCK







1;


=pod

=head1 NAME

Shipment::GSO::WSDL::Types::SubmitShipmentRequest

=head1 DESCRIPTION

Perl data type class for the XML Schema defined complexType
SubmitShipmentRequest from the namespace http://gso.com/GsoShipWS.






=head2 PROPERTIES

The following properties may be accessed using get_PROPERTY / set_PROPERTY
methods:

=over

=item * Package


=item * Notification


=item * ShipmentLabel




=back


=head1 METHODS

=head2 new

Constructor. The following data structure may be passed to new():

 { # Shipment::GSO::WSDL::Types::SubmitShipmentRequest
   Package =>  { # Shipment::GSO::WSDL::Types::Package
     AccountNumber =>  $some_value, # int
     TrackingNumber =>  $some_value, # string
     ShipperCompany =>  $some_value, # string
     ShipperContact =>  $some_value, # string
     ShipperPhone =>  $some_value, # string
     ShipperEmail =>  $some_value, # string
     PickupAddress1 =>  $some_value, # string
     PickupAddress2 =>  $some_value, # string
     PickupCity =>  $some_value, # string
     PickupState =>  $some_value, # string
     PickupZip =>  $some_value, # string
     ShipToCompany =>  $some_value, # string
     ShipToAttention =>  $some_value, # string
     ShipToPhone =>  $some_value, # string
     ShipToEmail =>  $some_value, # string
     DeliveryAddress1 =>  $some_value, # string
     DeliveryAddress2 =>  $some_value, # string
     DeliveryCity =>  $some_value, # string
     DeliveryState =>  $some_value, # string
     DeliveryZip =>  $some_value, # string
     ServiceCode =>  $some_value, # string
     ShipmentReference =>  $some_value, # string
     DeclaredValue =>  $some_value, # decimal
     CODValue =>  $some_value, # decimal
     SpecialInstructions =>  $some_value, # string
     Weight =>  $some_value, # decimal
     SignatureCode => $some_value, # SignatureType
     AddnShipperReference1 =>  $some_value, # string
     AddnShipperReference2 =>  $some_value, # string
   },
   Notification =>  { # Shipment::GSO::WSDL::Types::Notification
     ShipmentNotification =>  $some_value, # string
     ExceptionNotification =>  $some_value, # string
     DeliveryNotification =>  $some_value, # string
     ReceiptNotification =>  $some_value, # string
     ShipmentNotificationComments =>  $some_value, # string
     ExceptionNotificationComments =>  $some_value, # string
     DeliveryNotificationComments =>  $some_value, # string
     ReceiptNotificationComments =>  $some_value, # string
   },
   ShipmentLabel =>  { # Shipment::GSO::WSDL::Types::ShipmentLabel
     Type => $some_value, # LabelType
   },
 },




=head1 AUTHOR

Generated by SOAP::WSDL

=cut

