package Shipment::GSO::WSDL::Types::SubmitShippingSupplyOrderResult;
use strict;
use warnings;


__PACKAGE__->_set_element_form_qualified(1);

sub get_xmlns { 'http://gso.com/GsoShipWS' };

our $XML_ATTRIBUTE_CLASS;
undef $XML_ATTRIBUTE_CLASS;

sub __get_attr_class {
    return $XML_ATTRIBUTE_CLASS;
}

use Class::Std::Fast::Storable constructor => 'none';
use base qw(SOAP::WSDL::XSD::Typelib::ComplexType);

Class::Std::initialize();

{ # BLOCK to scope variables

my %SubmitShippingSupplyOrderInfo_of :ATTR(:get<SubmitShippingSupplyOrderInfo>);
my %Result_of :ATTR(:get<Result>);

__PACKAGE__->_factory(
    [ qw(        SubmitShippingSupplyOrderInfo
        Result

    ) ],
    {
        'SubmitShippingSupplyOrderInfo' => \%SubmitShippingSupplyOrderInfo_of,
        'Result' => \%Result_of,
    },
    {
        'SubmitShippingSupplyOrderInfo' => 'Shipment::GSO::WSDL::Types::SubmitShippingSupplyOrderInfo',
        'Result' => 'Shipment::GSO::WSDL::Types::Result',
    },
    {

        'SubmitShippingSupplyOrderInfo' => 'SubmitShippingSupplyOrderInfo',
        'Result' => 'Result',
    }
);

} # end BLOCK







1;


=pod

=head1 NAME

Shipment::GSO::WSDL::Types::SubmitShippingSupplyOrderResult

=head1 DESCRIPTION

Perl data type class for the XML Schema defined complexType
SubmitShippingSupplyOrderResult from the namespace http://gso.com/GsoShipWS.






=head2 PROPERTIES

The following properties may be accessed using get_PROPERTY / set_PROPERTY
methods:

=over

=item * SubmitShippingSupplyOrderInfo


=item * Result




=back


=head1 METHODS

=head2 new

Constructor. The following data structure may be passed to new():

 { # Shipment::GSO::WSDL::Types::SubmitShippingSupplyOrderResult
   SubmitShippingSupplyOrderInfo =>  { # Shipment::GSO::WSDL::Types::SubmitShippingSupplyOrderInfo
     OrderId =>  $some_value, # int
   },
   Result =>  { # Shipment::GSO::WSDL::Types::Result
     Code =>  $some_value, # int
     Message =>  $some_value, # string
   },
 },




=head1 AUTHOR

Generated by SOAP::WSDL

=cut

