package Shipment::GSO::WSDL::Types::SupplyOrder;
use strict;
use warnings;


__PACKAGE__->_set_element_form_qualified(1);

sub get_xmlns { 'http://gso.com/GsoShipWS' };

our $XML_ATTRIBUTE_CLASS;
undef $XML_ATTRIBUTE_CLASS;

sub __get_attr_class {
    return $XML_ATTRIBUTE_CLASS;
}

use Class::Std::Fast::Storable constructor => 'none';
use base qw(SOAP::WSDL::XSD::Typelib::ComplexType);

Class::Std::initialize();

{ # BLOCK to scope variables

my %AccountNumber_of :ATTR(:get<AccountNumber>);
my %ShipToCompany_of :ATTR(:get<ShipToCompany>);
my %ShipToAttention_of :ATTR(:get<ShipToAttention>);
my %ShipToPhone_of :ATTR(:get<ShipToPhone>);
my %ShipToEmail_of :ATTR(:get<ShipToEmail>);
my %DeliveryAddress1_of :ATTR(:get<DeliveryAddress1>);
my %DeliveryAddress2_of :ATTR(:get<DeliveryAddress2>);
my %DeliveryCity_of :ATTR(:get<DeliveryCity>);
my %DeliveryState_of :ATTR(:get<DeliveryState>);
my %DeliveryZip_of :ATTR(:get<DeliveryZip>);
my %OrderNotes_of :ATTR(:get<OrderNotes>);
my %DeliveryNotes_of :ATTR(:get<DeliveryNotes>);

__PACKAGE__->_factory(
    [ qw(        AccountNumber
        ShipToCompany
        ShipToAttention
        ShipToPhone
        ShipToEmail
        DeliveryAddress1
        DeliveryAddress2
        DeliveryCity
        DeliveryState
        DeliveryZip
        OrderNotes
        DeliveryNotes

    ) ],
    {
        'AccountNumber' => \%AccountNumber_of,
        'ShipToCompany' => \%ShipToCompany_of,
        'ShipToAttention' => \%ShipToAttention_of,
        'ShipToPhone' => \%ShipToPhone_of,
        'ShipToEmail' => \%ShipToEmail_of,
        'DeliveryAddress1' => \%DeliveryAddress1_of,
        'DeliveryAddress2' => \%DeliveryAddress2_of,
        'DeliveryCity' => \%DeliveryCity_of,
        'DeliveryState' => \%DeliveryState_of,
        'DeliveryZip' => \%DeliveryZip_of,
        'OrderNotes' => \%OrderNotes_of,
        'DeliveryNotes' => \%DeliveryNotes_of,
    },
    {
        'AccountNumber' => 'SOAP::WSDL::XSD::Typelib::Builtin::int',
        'ShipToCompany' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
        'ShipToAttention' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
        'ShipToPhone' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
        'ShipToEmail' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
        'DeliveryAddress1' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
        'DeliveryAddress2' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
        'DeliveryCity' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
        'DeliveryState' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
        'DeliveryZip' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
        'OrderNotes' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
        'DeliveryNotes' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
    },
    {

        'AccountNumber' => 'AccountNumber',
        'ShipToCompany' => 'ShipToCompany',
        'ShipToAttention' => 'ShipToAttention',
        'ShipToPhone' => 'ShipToPhone',
        'ShipToEmail' => 'ShipToEmail',
        'DeliveryAddress1' => 'DeliveryAddress1',
        'DeliveryAddress2' => 'DeliveryAddress2',
        'DeliveryCity' => 'DeliveryCity',
        'DeliveryState' => 'DeliveryState',
        'DeliveryZip' => 'DeliveryZip',
        'OrderNotes' => 'OrderNotes',
        'DeliveryNotes' => 'DeliveryNotes',
    }
);

} # end BLOCK







1;


=pod

=head1 NAME

Shipment::GSO::WSDL::Types::SupplyOrder

=head1 DESCRIPTION

Perl data type class for the XML Schema defined complexType
SupplyOrder from the namespace http://gso.com/GsoShipWS.






=head2 PROPERTIES

The following properties may be accessed using get_PROPERTY / set_PROPERTY
methods:

=over

=item * AccountNumber


=item * ShipToCompany


=item * ShipToAttention


=item * ShipToPhone


=item * ShipToEmail


=item * DeliveryAddress1


=item * DeliveryAddress2


=item * DeliveryCity


=item * DeliveryState


=item * DeliveryZip


=item * OrderNotes


=item * DeliveryNotes




=back


=head1 METHODS

=head2 new

Constructor. The following data structure may be passed to new():

 { # Shipment::GSO::WSDL::Types::SupplyOrder
   AccountNumber =>  $some_value, # int
   ShipToCompany =>  $some_value, # string
   ShipToAttention =>  $some_value, # string
   ShipToPhone =>  $some_value, # string
   ShipToEmail =>  $some_value, # string
   DeliveryAddress1 =>  $some_value, # string
   DeliveryAddress2 =>  $some_value, # string
   DeliveryCity =>  $some_value, # string
   DeliveryState =>  $some_value, # string
   DeliveryZip =>  $some_value, # string
   OrderNotes =>  $some_value, # string
   DeliveryNotes =>  $some_value, # string
 },




=head1 AUTHOR

Generated by SOAP::WSDL

=cut

