package Shipment::GSO::WSDL::Types::TrackShipmentInfo;
use strict;
use warnings;


__PACKAGE__->_set_element_form_qualified(1);

sub get_xmlns { 'http://gso.com/GsoShipWS' };

our $XML_ATTRIBUTE_CLASS;
undef $XML_ATTRIBUTE_CLASS;

sub __get_attr_class {
    return $XML_ATTRIBUTE_CLASS;
}

use Class::Std::Fast::Storable constructor => 'none';
use base qw(SOAP::WSDL::XSD::Typelib::ComplexType);

Class::Std::initialize();

{ # BLOCK to scope variables

my %TrackingNumber_of :ATTR(:get<TrackingNumber>);
my %ShipToCompany_of :ATTR(:get<ShipToCompany>);
my %DeliveryCity_of :ATTR(:get<DeliveryCity>);
my %DeliveryState_of :ATTR(:get<DeliveryState>);
my %DeliveryZip_of :ATTR(:get<DeliveryZip>);
my %ServiceCode_of :ATTR(:get<ServiceCode>);
my %ShipmentReference_of :ATTR(:get<ShipmentReference>);
my %Weight_of :ATTR(:get<Weight>);

__PACKAGE__->_factory(
    [ qw(        TrackingNumber
        ShipToCompany
        DeliveryCity
        DeliveryState
        DeliveryZip
        ServiceCode
        ShipmentReference
        Weight

    ) ],
    {
        'TrackingNumber' => \%TrackingNumber_of,
        'ShipToCompany' => \%ShipToCompany_of,
        'DeliveryCity' => \%DeliveryCity_of,
        'DeliveryState' => \%DeliveryState_of,
        'DeliveryZip' => \%DeliveryZip_of,
        'ServiceCode' => \%ServiceCode_of,
        'ShipmentReference' => \%ShipmentReference_of,
        'Weight' => \%Weight_of,
    },
    {
        'TrackingNumber' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
        'ShipToCompany' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
        'DeliveryCity' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
        'DeliveryState' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
        'DeliveryZip' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
        'ServiceCode' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
        'ShipmentReference' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
        'Weight' => 'SOAP::WSDL::XSD::Typelib::Builtin::int',
    },
    {

        'TrackingNumber' => 'TrackingNumber',
        'ShipToCompany' => 'ShipToCompany',
        'DeliveryCity' => 'DeliveryCity',
        'DeliveryState' => 'DeliveryState',
        'DeliveryZip' => 'DeliveryZip',
        'ServiceCode' => 'ServiceCode',
        'ShipmentReference' => 'ShipmentReference',
        'Weight' => 'Weight',
    }
);

} # end BLOCK







1;


=pod

=head1 NAME

Shipment::GSO::WSDL::Types::TrackShipmentInfo

=head1 DESCRIPTION

Perl data type class for the XML Schema defined complexType
TrackShipmentInfo from the namespace http://gso.com/GsoShipWS.






=head2 PROPERTIES

The following properties may be accessed using get_PROPERTY / set_PROPERTY
methods:

=over

=item * TrackingNumber


=item * ShipToCompany


=item * DeliveryCity


=item * DeliveryState


=item * DeliveryZip


=item * ServiceCode


=item * ShipmentReference


=item * Weight




=back


=head1 METHODS

=head2 new

Constructor. The following data structure may be passed to new():

 { # Shipment::GSO::WSDL::Types::TrackShipmentInfo
   TrackingNumber =>  $some_value, # string
   ShipToCompany =>  $some_value, # string
   DeliveryCity =>  $some_value, # string
   DeliveryState =>  $some_value, # string
   DeliveryZip =>  $some_value, # string
   ServiceCode =>  $some_value, # string
   ShipmentReference =>  $some_value, # string
   Weight =>  $some_value, # int
 },




=head1 AUTHOR

Generated by SOAP::WSDL

=cut

