package Shipment::GSO::WSDL::Types::TrackShipmentResult;
use strict;
use warnings;


__PACKAGE__->_set_element_form_qualified(1);

sub get_xmlns { 'http://gso.com/GsoShipWS' };

our $XML_ATTRIBUTE_CLASS;
undef $XML_ATTRIBUTE_CLASS;

sub __get_attr_class {
    return $XML_ATTRIBUTE_CLASS;
}

use Class::Std::Fast::Storable constructor => 'none';
use base qw(SOAP::WSDL::XSD::Typelib::ComplexType);

Class::Std::initialize();

{ # BLOCK to scope variables

my %TrackShipmentInfo_of :ATTR(:get<TrackShipmentInfo>);
my %Delivery_of :ATTR(:get<Delivery>);
my %TransitNotes_of :ATTR(:get<TransitNotes>);
my %Result_of :ATTR(:get<Result>);

__PACKAGE__->_factory(
    [ qw(        TrackShipmentInfo
        Delivery
        TransitNotes
        Result

    ) ],
    {
        'TrackShipmentInfo' => \%TrackShipmentInfo_of,
        'Delivery' => \%Delivery_of,
        'TransitNotes' => \%TransitNotes_of,
        'Result' => \%Result_of,
    },
    {
        'TrackShipmentInfo' => 'Shipment::GSO::WSDL::Types::TrackShipmentInfo',
        'Delivery' => 'Shipment::GSO::WSDL::Types::Delivery',
        'TransitNotes' => 'Shipment::GSO::WSDL::Types::ArrayOfTransitNote',
        'Result' => 'Shipment::GSO::WSDL::Types::Result',
    },
    {

        'TrackShipmentInfo' => 'TrackShipmentInfo',
        'Delivery' => 'Delivery',
        'TransitNotes' => 'TransitNotes',
        'Result' => 'Result',
    }
);

} # end BLOCK







1;


=pod

=head1 NAME

Shipment::GSO::WSDL::Types::TrackShipmentResult

=head1 DESCRIPTION

Perl data type class for the XML Schema defined complexType
TrackShipmentResult from the namespace http://gso.com/GsoShipWS.






=head2 PROPERTIES

The following properties may be accessed using get_PROPERTY / set_PROPERTY
methods:

=over

=item * TrackShipmentInfo


=item * Delivery


=item * TransitNotes


=item * Result




=back


=head1 METHODS

=head2 new

Constructor. The following data structure may be passed to new():

 { # Shipment::GSO::WSDL::Types::TrackShipmentResult
   TrackShipmentInfo =>  { # Shipment::GSO::WSDL::Types::TrackShipmentInfo
     TrackingNumber =>  $some_value, # string
     ShipToCompany =>  $some_value, # string
     DeliveryCity =>  $some_value, # string
     DeliveryState =>  $some_value, # string
     DeliveryZip =>  $some_value, # string
     ServiceCode =>  $some_value, # string
     ShipmentReference =>  $some_value, # string
     Weight =>  $some_value, # int
   },
   Delivery =>  { # Shipment::GSO::WSDL::Types::Delivery
     ShipDate =>  $some_value, # dateTime
     ScheduledDate =>  $some_value, # dateTime
     DeliveryDate =>  $some_value, # dateTime
     TransitStatus =>  $some_value, # string
     DeliveryTime =>  $some_value, # string
     SignedBy =>  $some_value, # string
     Signature =>  $some_value, # base64Binary
   },
   TransitNotes =>  { # Shipment::GSO::WSDL::Types::ArrayOfTransitNote
     TransitNote =>  { # Shipment::GSO::WSDL::Types::TransitNote
       EventDate =>  $some_value, # dateTime
       Comments =>  $some_value, # string
     },
   },
   Result =>  { # Shipment::GSO::WSDL::Types::Result
     Code =>  $some_value, # int
     Message =>  $some_value, # string
   },
 },




=head1 AUTHOR

Generated by SOAP::WSDL

=cut

