package Shipment::GSO::WSDL::Types::TrackingInfo;
use strict;
use warnings;


__PACKAGE__->_set_element_form_qualified(1);

sub get_xmlns { 'http://gso.com/GsoShipWS' };

our $XML_ATTRIBUTE_CLASS;
undef $XML_ATTRIBUTE_CLASS;

sub __get_attr_class {
    return $XML_ATTRIBUTE_CLASS;
}

use Class::Std::Fast::Storable constructor => 'none';
use base qw(SOAP::WSDL::XSD::Typelib::ComplexType);

Class::Std::initialize();

{ # BLOCK to scope variables

my %OrderId_of :ATTR(:get<OrderId>);
my %OrderDate_of :ATTR(:get<OrderDate>);
my %OrderStatus_of :ATTR(:get<OrderStatus>);
my %ShipDate_of :ATTR(:get<ShipDate>);
my %TrackingNumber_of :ATTR(:get<TrackingNumber>);

__PACKAGE__->_factory(
    [ qw(        OrderId
        OrderDate
        OrderStatus
        ShipDate
        TrackingNumber

    ) ],
    {
        'OrderId' => \%OrderId_of,
        'OrderDate' => \%OrderDate_of,
        'OrderStatus' => \%OrderStatus_of,
        'ShipDate' => \%ShipDate_of,
        'TrackingNumber' => \%TrackingNumber_of,
    },
    {
        'OrderId' => 'SOAP::WSDL::XSD::Typelib::Builtin::int',
        'OrderDate' => 'SOAP::WSDL::XSD::Typelib::Builtin::dateTime',
        'OrderStatus' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
        'ShipDate' => 'SOAP::WSDL::XSD::Typelib::Builtin::dateTime',
        'TrackingNumber' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
    },
    {

        'OrderId' => 'OrderId',
        'OrderDate' => 'OrderDate',
        'OrderStatus' => 'OrderStatus',
        'ShipDate' => 'ShipDate',
        'TrackingNumber' => 'TrackingNumber',
    }
);

} # end BLOCK







1;


=pod

=head1 NAME

Shipment::GSO::WSDL::Types::TrackingInfo

=head1 DESCRIPTION

Perl data type class for the XML Schema defined complexType
TrackingInfo from the namespace http://gso.com/GsoShipWS.






=head2 PROPERTIES

The following properties may be accessed using get_PROPERTY / set_PROPERTY
methods:

=over

=item * OrderId


=item * OrderDate


=item * OrderStatus


=item * ShipDate


=item * TrackingNumber




=back


=head1 METHODS

=head2 new

Constructor. The following data structure may be passed to new():

 { # Shipment::GSO::WSDL::Types::TrackingInfo
   OrderId =>  $some_value, # int
   OrderDate =>  $some_value, # dateTime
   OrderStatus =>  $some_value, # string
   ShipDate =>  $some_value, # dateTime
   TrackingNumber =>  $some_value, # string
 },




=head1 AUTHOR

Generated by SOAP::WSDL

=cut

